/* The Front Office — league PWA client.
   Renders site.json (regenerated by the bot at every sync) into the five tabs.
   No framework, no build step — this file IS the app. */

"use strict";

/* Real NFL team palettes keyed by EA's abbrName (note EA quirks: AZ not ARI).
   primary = the brand color used for rails/rings; text stays theme-controlled. */
const TEAM_COLORS = {
  AZ:  { primary: "#97233F", secondary: "#FFB612" },
  ATL: { primary: "#A71930", secondary: "#000000" },
  BAL: { primary: "#241773", secondary: "#9E7C0C" },
  BUF: { primary: "#00338D", secondary: "#C60C30" },
  CAR: { primary: "#0085CA", secondary: "#101820" },
  CHI: { primary: "#0B162A", secondary: "#C83803" },
  CIN: { primary: "#FB4F14", secondary: "#000000" },
  CLE: { primary: "#311D00", secondary: "#FF3C00" },
  DAL: { primary: "#003594", secondary: "#869397" },
  DEN: { primary: "#FB4F14", secondary: "#002244" },
  DET: { primary: "#0076B6", secondary: "#B0B7BC" },
  GB:  { primary: "#203731", secondary: "#FFB612" },
  HOU: { primary: "#03202F", secondary: "#A71930" },
  IND: { primary: "#002C5F", secondary: "#A2AAAD" },
  JAX: { primary: "#006778", secondary: "#D7A22A" },
  KC:  { primary: "#E31837", secondary: "#FFB81C" },
  LAC: { primary: "#0080C6", secondary: "#FFC20E" },
  LAR: { primary: "#003594", secondary: "#FFA300" },
  LV:  { primary: "#000000", secondary: "#A5ACAF" },
  MIA: { primary: "#008E97", secondary: "#FC4C02" },
  MIN: { primary: "#4F2683", secondary: "#FFC62F" },
  NE:  { primary: "#002244", secondary: "#C60C30" },
  NO:  { primary: "#D3BC8D", secondary: "#101820" },
  NYG: { primary: "#0B2265", secondary: "#A71930" },
  NYJ: { primary: "#125740", secondary: "#000000" },
  PHI: { primary: "#004C54", secondary: "#A5ACAF" },
  PIT: { primary: "#FFB612", secondary: "#101820" },
  SEA: { primary: "#002244", secondary: "#69BE28" },
  SF:  { primary: "#AA0000", secondary: "#B3995D" },
  TB:  { primary: "#D50A0A", secondary: "#34302B" },
  TEN: { primary: "#0C2340", secondary: "#4B92DB" },
  WAS: { primary: "#5A1414", secondary: "#FFB612" },
};

/* ESPN logo slugs, where they differ from lowercase EA abbr. */
const LOGO_SLUGS = { AZ: "ari", WAS: "wsh" };

function logoUrl(abbr) {
  const slug = LOGO_SLUGS[abbr] || abbr.toLowerCase();
  return `https://a.espncdn.com/i/teamlogos/nfl/500/${slug}.png`;
}

function portraitUrl(portraitId) {
  return `https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/${portraitId}.png?im=FaceCrop,padding=0.7`;
}

function teamColor(abbr) {
  return (TEAM_COLORS[abbr] || { primary: "#5c6b7d", secondary: "#93a1b3" }).primary;
}

/* A primary that's too dark to read as a rail on the dark theme gets its
   secondary instead (Bears navy, Raiders black, Texans navy...). */
function railColor(abbr) {
  const c = TEAM_COLORS[abbr];
  if (!c) return "#5c6b7d";
  return luminance(c.primary) < 0.05 ? c.secondary : c.primary;
}

function luminance(hex) {
  const n = parseInt(hex.slice(1), 16);
  const r = (n >> 16) / 255, g = ((n >> 8) & 255) / 255, b = (n & 255) / 255;
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/* ---------- State ---------- */

let DATA = null;
const teamIndex = new Map();

function team(id) { return teamIndex.get(id) || { abbr: "?", nick: "Unknown", city: "", division: "" }; }

function record(teamId) {
  const s = (DATA.standings || []).find((r) => r.teamId === teamId);
  if (!s) return "";
  return s.ties ? `${s.wins}-${s.losses}-${s.ties}` : `${s.wins}-${s.losses}`;
}

/* ---------- Tiny DOM helpers ---------- */

function el(tag, cls, text) {
  const node = document.createElement(tag);
  if (cls) node.className = cls;
  if (text !== undefined) node.textContent = text;
  return node;
}

function svgIcon(path, cls) {
  const s = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  s.setAttribute("viewBox", "0 0 24 24");
  if (cls) s.setAttribute("class", cls);
  const p = document.createElementNS("http://www.w3.org/2000/svg", "path");
  p.setAttribute("d", path);
  s.appendChild(p);
  return s;
}

function logoImg(abbr, cls) {
  const img = el("img", cls || "logo");
  img.src = logoUrl(abbr);
  img.alt = abbr;
  img.loading = "lazy";
  img.onerror = () => { img.style.visibility = "hidden"; };
  return img;
}

function avatar(row, sizeCls) {
  const ring = teamColor(team(row.teamId).abbr);
  if (row.portraitId) {
    const img = el("img", "avatar " + (sizeCls || ""));
    img.style.setProperty("--ring", ring);
    img.src = portraitUrl(row.portraitId);
    img.alt = row.name;
    img.loading = "lazy";
    img.onerror = () => img.replaceWith(initialsAvatar(row, ring, sizeCls));
    return img;
  }
  return initialsAvatar(row, ring, sizeCls);
}

function initialsAvatar(row, ring, sizeCls) {
  const d = el("div", "avatar initials " + (sizeCls || ""));
  d.style.setProperty("--ring", ring);
  d.textContent = row.name.split(" ").map((w) => w[0] || "").join("").slice(0, 2).toUpperCase();
  return d;
}

function sectionHead(title, sub) {
  const head = el("div", "section-head");
  head.appendChild(el("div", "section-title", title));
  if (sub) head.appendChild(el("div", "section-sub", sub));
  return head;
}

function timeAgo(iso) {
  const mins = Math.max(1, Math.round((Date.now() - new Date(iso).getTime()) / 60000));
  if (mins < 60) return `${mins}m`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs}h`;
  return `${Math.round(hrs / 24)}d`;
}

/* ---------- Game card ---------- */

const DISCORD_PATH = "M20.3 4.4A19.8 19.8 0 0 0 15.4 3l-.6 1.2a18 18 0 0 0-5.5 0L8.6 3a19.8 19.8 0 0 0-4.9 1.5A20.4 20.4 0 0 0 .2 18.1a19.9 19.9 0 0 0 6 3l1.2-2a12.9 12.9 0 0 1-2-.9l.5-.4a14.2 14.2 0 0 0 12.2 0l.5.4a12.9 12.9 0 0 1-2 .9l1.2 2a19.9 19.9 0 0 0 6-3A20.4 20.4 0 0 0 20.3 4.4ZM8 14.7c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Zm8 0c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Z";

/* Side-by-side matchup panel (tale of the tape) shown when a game card is tapped. */
function matchupPanel(g, away, home) {
  const panel = el("div", "matchup-panel");
  const sA = (DATA.standings || []).find((s) => s.teamId === g.awayTeamId);
  const sB = (DATA.standings || []).find((s) => s.teamId === g.homeTeamId);
  const rA = (DATA.rankings || []).find((r) => r.teamId === g.awayTeamId);
  const rB = (DATA.rankings || []).find((r) => r.teamId === g.homeTeamId);

  const rows = [
    { label: "Record", a: record(g.awayTeamId) || "—", b: record(g.homeTeamId) || "—", betterA: sA && sB ? sA.wins - sA.losses > sB.wins - sB.losses : null },
    { label: "Team OVR", a: away.ovr ?? "—", b: home.ovr ?? "—", betterA: (away.ovr ?? 0) > (home.ovr ?? 0) },
    { label: "Power Rank", a: rA ? "#" + rA.rank : "—", b: rB ? "#" + rB.rank : "—", betterA: rA && rB ? rA.rank < rB.rank : null },
    { label: "PPG", a: sA?.ptsFor ?? "—", b: sB?.ptsFor ?? "—", betterA: (sA?.ptsFor ?? 0) > (sB?.ptsFor ?? 0) },
    { label: "PA/G", a: sA?.ptsAgainst ?? "—", b: sB?.ptsAgainst ?? "—", betterA: (sA?.ptsAgainst ?? 99) < (sB?.ptsAgainst ?? 99) },
  ];
  for (const row of rows) {
    if (row.a === row.b) row.betterA = null;
    const r = el("div", "tape-row");
    r.appendChild(el("span", "tape-val" + (row.betterA === true ? " better" : ""), String(row.a)));
    r.appendChild(el("span", "tape-label", row.label));
    r.appendChild(el("span", "tape-val right" + (row.betterA === false ? " better" : ""), String(row.b)));
    panel.appendChild(r);
  }

  // Earlier meeting this season, from the recorded history
  for (const w of DATA.history || []) {
    for (const h of w.games) {
      if (h.kind !== "played") continue;
      const same = (h.awayTeamId === g.awayTeamId && h.homeTeamId === g.homeTeamId) || (h.awayTeamId === g.homeTeamId && h.homeTeamId === g.awayTeamId);
      if (same && !(g.played && h.awayScore === g.awayScore && h.homeScore === g.homeScore && h.awayTeamId === g.awayTeamId)) {
        panel.appendChild(el("div", "tape-h2h", `Earlier this season (${w.label}): ${team(h.awayTeamId).abbr} ${h.awayScore} — ${h.homeScore} ${team(h.homeTeamId).abbr}`));
      }
    }
  }

  if (g.channelUrl && !g.played) {
    const cta = el("a", "matchup-cta", "Open game channel →");
    cta.href = g.channelUrl;
    cta.target = "_blank";
    cta.rel = "noopener";
    cta.addEventListener("click", (e) => e.stopPropagation());
    panel.appendChild(cta);
  }
  return panel;
}

function gameCard(g) {
  const card = el("div", "card game-toggle" + (g.isGotw ? " gotw" : ""));
  card.addEventListener("click", () => {
    expandedGame = expandedGame === g.scheduleId ? null : g.scheduleId;
    render();
  });

  const away = team(g.awayTeamId), home = team(g.homeTeamId);

  if (g.isGotw) {
    const eyebrow = el("div", "gotw-eyebrow");
    eyebrow.appendChild(svgIcon("M12 2l2.4 4.9 5.4.8-3.9 3.8.9 5.4L12 14.3 7.2 16.9l.9-5.4L4.2 7.7l5.4-.8z"));
    eyebrow.appendChild(document.createTextNode("Game of the Week"));
    card.appendChild(eyebrow);

    const billboard = el("div", "gotw-billboard");
    billboard.style.setProperty("--bb-away", railColor(away.abbr));
    billboard.style.setProperty("--bb-home", railColor(home.abbr));
    billboard.appendChild(logoImg(away.abbr, "bb-logo"));
    billboard.appendChild(el("span", "gotw-vs", "VS"));
    billboard.appendChild(logoImg(home.abbr, "bb-logo"));
    card.appendChild(billboard);
  }
  const body = el("div", "game");
  body.style.setProperty("--rail", `linear-gradient(to bottom, ${railColor(away.abbr)} 0%, ${railColor(away.abbr)} 48%, ${railColor(home.abbr)} 52%, ${railColor(home.abbr)} 100%)`);
  body.appendChild(logoImg(home.abbr, "wm"));

  const decidedByForce = g.forced === "forceWin";
  const awayWon = decidedByForce ? g.forcedWinnerTeamId === g.awayTeamId : g.played && g.awayScore > g.homeScore;
  const homeWon = decidedByForce ? g.forcedWinnerTeamId === g.homeTeamId : g.played && g.homeScore > g.awayScore;
  const decided = g.played || decidedByForce || g.forced === "fairSim";

  for (const [t, score, won] of [[away, g.awayScore, awayWon], [home, g.homeScore, homeWon]]) {
    const row = el("div", "game-row" + (decided && !won && (awayWon || homeWon) ? " loser" : ""));
    row.appendChild(logoImg(t.abbr));
    const name = el("div", "team-name");
    name.appendChild(el("span", "nick", t.nick));
    const rec = record(t.teamId);
    if (rec) name.appendChild(el("span", "record", rec));
    row.appendChild(name);
    row.appendChild(el("span", "score", g.played ? String(score) : "—"));
    if (won) row.appendChild(el("span", "winner-tick"));
    body.appendChild(row);
  }

  const meta = el("div", "game-meta");
  if (g.forced === "forceWin") meta.appendChild(el("span", "chip forced", "Force Win"));
  else if (g.forced === "fairSim") meta.appendChild(el("span", "chip fairsim", "Fair Sim"));
  else if (g.played) meta.appendChild(el("span", "chip final", "Final"));
  else meta.appendChild(el("span", "chip live", "Scheduled"));
  meta.appendChild(el("span", "expand-hint", expandedGame === g.scheduleId ? "Hide matchup ▴" : "Matchup ▾"));
  body.appendChild(meta);
  card.appendChild(body);
  if (expandedGame === g.scheduleId) card.appendChild(matchupPanel(g, away, home));
  return card;
}

/* ---------- Tabs ---------- */

/* The ESPN-style scoreboard rail: one compact chip per game, horizontally
   scrollable, finals first (that's what people check the strip for). */
function scoreStrip(games) {
  const strip = el("div", "scorestrip");
  const ordered = games.slice().sort((a, b) => Number(b.played) - Number(a.played));
  for (const g of ordered) {
    const away = team(g.awayTeamId), home = team(g.homeTeamId);
    const chip = el(g.channelUrl ? "a" : "div", "scorechip");
    if (g.channelUrl) { chip.href = g.channelUrl; chip.target = "_blank"; chip.rel = "noopener"; }
    const decided = g.played;
    for (const [t, score, won] of [[away, g.awayScore, decided && g.awayScore > g.homeScore], [home, g.homeScore, decided && g.homeScore > g.awayScore]]) {
      const row = el("div", "sc-row" + (decided && !won ? " loser" : ""));
      row.appendChild(logoImg(t.abbr, "sc-logo"));
      row.appendChild(el("span", null, t.abbr));
      row.appendChild(el("span", "sc-score", decided ? String(score) : record(t.teamId)));
      chip.appendChild(row);
    }
    const status = g.isGotw ? "★ GOTW" : g.forced === "forceWin" ? "Force Win" : g.forced === "fairSim" ? "Fair Sim" : g.played ? "Final" : "Scheduled";
    chip.appendChild(el("div", "sc-status" + (g.isGotw ? " gotw" : g.played ? " final" : ""), status));
    strip.appendChild(chip);
  }
  return strip;
}

/* ---------- Front page (Home) ----------
   ESPN anatomy: score rail on top, a HERO, then a main scoreboard column with a
   right rail of Top Headlines / Injury Report / Transactions (rail stacks under
   on phones). The flash lives in the hero and the rail density, not the chrome. */

function heroCard(g) {
  const away = team(g.awayTeamId), home = team(g.homeTeamId);
  const hero = el(g.channelUrl ? "a" : "div", "hero");
  if (g.channelUrl) { hero.href = g.channelUrl; hero.target = "_blank"; hero.rel = "noopener"; }
  hero.style.setProperty("--bb-away", railColor(away.abbr));
  hero.style.setProperty("--bb-home", railColor(home.abbr));
  hero.appendChild(logoImg(away.abbr, "wm wm-away"));
  hero.appendChild(logoImg(home.abbr, "wm wm-home"));

  const eyebrow = el("div", "hero-eyebrow");
  eyebrow.appendChild(svgIcon("M12 2l2.4 4.9 5.4.8-3.9 3.8.9 5.4L12 14.3 7.2 16.9l.9-5.4L4.2 7.7l5.4-.8z"));
  eyebrow.appendChild(document.createTextNode(`Game of the Week · ${DATA.week.label}`));
  hero.appendChild(eyebrow);

  const face = el("div", "hero-face");
  for (const [t, side] of [[away, "away"], [home, "home"]]) {
    const block = el("div", "hero-team " + side);
    block.appendChild(logoImg(t.abbr, "hero-logo"));
    const name = el("div", "hero-name");
    name.appendChild(el("span", "hero-nick", t.nick.toUpperCase()));
    name.appendChild(el("span", "hero-rec", record(t.teamId) || t.abbr));
    block.appendChild(name);
    face.appendChild(block);
    if (side === "away") face.appendChild(el("div", "hero-vs", "VS"));
  }
  hero.appendChild(face);

  const meta = el("div", "hero-meta");
  const decided = g.played;
  meta.appendChild(el("span", "hero-status", decided ? `FINAL · ${away.abbr} ${g.awayScore} — ${home.abbr} ${g.homeScore}` : "THIS WEEK"));
  if (g.channelUrl) meta.appendChild(el("span", "hero-cta", "Open game channel →"));
  hero.appendChild(meta);
  return hero;
}

function railCard(title, rows) {
  const card = el("div", "card rail-card");
  card.appendChild(el("div", "rail-head", title));
  for (const row of rows) card.appendChild(row);
  return card;
}

function headlineRow(post) {
  const row = el("div", "headline-item");
  const text = post.text.length > 120 ? post.text.slice(0, post.text.lastIndexOf(" ", 120)) + "…" : post.text;
  row.appendChild(el("div", "headline-text", text));
  row.appendChild(el("div", "headline-by", `${post.name} · ${timeAgo(post.postedAt)}`));
  return row;
}

function injuryRow(inj) {
  const row = el("div", "wire-row");
  row.appendChild(avatar({ name: inj.name, teamId: inj.teamId, portraitId: inj.portraitId }));
  const who = el("div", "wire-who");
  who.appendChild(el("div", "wire-name", inj.name));
  who.appendChild(el("div", "wire-sub", `${inj.pos} · ${team(inj.teamId).abbr}`));
  row.appendChild(who);
  row.appendChild(el("span", "wire-tag out", inj.weeksOut >= 17 ? "OUT · SEASON" : `OUT ~${inj.weeksOut} WK${inj.weeksOut === 1 ? "" : "S"}`));
  return row;
}

const TX_LABEL = { signed: "SIGN", dropped: "CUT", traded: "TRADE" };

function txRow(tx) {
  const row = el("div", "wire-row");
  row.appendChild(el("span", "wire-tag tx-" + tx.kind, TX_LABEL[tx.kind] || tx.kind.toUpperCase()));
  const who = el("div", "wire-who");
  who.appendChild(el("div", "wire-name", `${tx.playerName}`));
  const from = tx.fromTeamId ? team(tx.fromTeamId).abbr : "FA";
  const to = tx.toTeamId ? team(tx.toTeamId).abbr : "FA";
  who.appendChild(el("div", "wire-sub", `${tx.position} · ${from} → ${to}`));
  row.appendChild(who);
  row.appendChild(el("span", "wire-time", timeAgo(tx.at)));
  return row;
}

/* One finished game as a compact history line: winner bold with the red tick. */
function historyRow(g) {
  const r = el("div", "hist-row");
  if (g.kind === "played") {
    const away = team(g.awayTeamId), home = team(g.homeTeamId);
    const awayWon = g.awayScore > g.homeScore, homeWon = g.homeScore > g.awayScore;
    const side = (t, score, won) => {
      const s = el("div", "hist-side" + (won ? " won" : ""));
      s.appendChild(logoImg(t.abbr, "hist-logo"));
      s.appendChild(el("span", "hist-abbr", t.abbr));
      s.appendChild(el("span", "hist-score", String(score)));
      return s;
    };
    r.appendChild(side(away, g.awayScore, awayWon));
    r.appendChild(el("span", "hist-at", "@"));
    r.appendChild(side(home, g.homeScore, homeWon));
  } else if (g.kind === "forceWin") {
    const w = team(g.winnerTeamId), l = team(g.loserTeamId);
    r.appendChild(logoImg(w.abbr, "hist-logo"));
    r.appendChild(el("span", "hist-text", `${w.abbr} def. ${l.abbr}`));
    r.appendChild(el("span", "chip forced", "Force Win"));
  } else {
    const a = team(g.awayTeamId), h = team(g.homeTeamId);
    r.appendChild(logoImg(a.abbr, "hist-logo"));
    r.appendChild(el("span", "hist-text", `${a.abbr} @ ${h.abbr}`));
    r.appendChild(el("span", "chip fairsim", "Fair Sim"));
  }
  return r;
}

function renderHome(view) {
  const games = (DATA.week.games || []).slice();
  const gotw = games.filter((g) => g.isGotw);
  const rest = games.filter((g) => !g.isGotw);

  if (games.length) view.appendChild(scoreStrip(games));

  const page = el("div", "front");
  const main = el("div", "front-main");
  const rail = el("div", "front-rail");

  if (gotw.length) main.appendChild(heroCard(gotw[0]));

  const pastWeeks = (DATA.history || []).filter((w) => w.label !== DATA.week.label);
  main.appendChild(sectionHead("Scoreboard", scoreWeek ? "" : `${games.length} games`));
  if (pastWeeks.length) {
    const pills = el("div", "week-pills");
    for (const w of pastWeeks) {
      const key = `${w.stage}-${w.week}`;
      const pill = el("button", "week-pill" + (scoreWeek === key ? " active" : ""), w.label.replace("Preseason ", "P"));
      pill.type = "button";
      pill.addEventListener("click", () => { scoreWeek = scoreWeek === key ? null : key; render(); });
      pills.appendChild(pill);
    }
    const now = el("button", "week-pill" + (scoreWeek === null ? " active" : ""), "This Week");
    now.type = "button";
    now.addEventListener("click", () => { scoreWeek = null; render(); });
    pills.appendChild(now);
    main.appendChild(pills);
  }
  if (scoreWeek) {
    const w = pastWeeks.find((x) => `${x.stage}-${x.week}` === scoreWeek);
    const card = el("div", "card");
    for (const g of w ? w.games : []) card.appendChild(historyRow(g));
    if (!w || !w.games.length) card.appendChild(el("div", "empty", "No recorded results for that week."));
    main.appendChild(card);
  } else {
    if (!games.length) main.appendChild(el("div", "empty", "No games on the schedule yet — check back after the next sync."));
    const grid = el("div", "grid games-grid");
    for (const g of [...gotw.slice(1), ...rest]) grid.appendChild(gameCard(g));
    main.appendChild(grid);
  }

  if ((DATA.news || []).length) {
    rail.appendChild(sectionHead("Top Headlines", ""));
    rail.appendChild(railCard("From the insiders", DATA.news.slice(0, 6).map(headlineRow)));
  }
  if ((DATA.injuries || []).length) {
    rail.appendChild(sectionHead("Injury Report", ""));
    rail.appendChild(railCard("Currently out", DATA.injuries.slice(0, 8).map(injuryRow)));
  }
  if ((DATA.transactions || []).length) {
    rail.appendChild(sectionHead("Transactions", ""));
    rail.appendChild(railCard("The wire", DATA.transactions.slice(0, 8).map(txRow)));
  }

  page.appendChild(main);
  if (rail.childNodes.length) { page.appendChild(rail); page.classList.add("has-rail"); }
  view.appendChild(page);
}

function renderStandings(view) {
  const byDivision = new Map();
  for (const row of DATA.standings || []) {
    if (!byDivision.has(row.division)) byDivision.set(row.division, []);
    byDivision.get(row.division).push(row);
  }
  if (!byDivision.size) { view.appendChild(el("div", "empty", "No standings yet.")); return; }
  const grid = el("div", "grid standings-grid");
  for (const [division, rows] of byDivision) {
    const block = el("div", "division-block");
    block.appendChild(el("div", "division-label", division));
    const card = el("div", "card");
    for (const row of rows) {
      const t = team(row.teamId);
      const r = el("button", "standings-row row-link");
      r.type = "button";
      r.addEventListener("click", () => openTeam(row.teamId));
      r.style.setProperty("--rail", railColor(t.abbr));
      r.appendChild(logoImg(t.abbr));
      r.appendChild(el("span", "name", t.nick));
      if (row.streak) {
        const w = row.streak > 0;
        r.appendChild(el("span", "streak " + (w ? "w" : "l"), (w ? "W" : "L") + Math.abs(row.streak)));
      }
      r.appendChild(el("span", "rec", row.ties ? `${row.wins}-${row.losses}-${row.ties}` : `${row.wins}-${row.losses}`));
      r.appendChild(el("span", "pts", `${row.ptsFor} PF · ${row.ptsAgainst} PA`));
      card.appendChild(r);
    }
    block.appendChild(card);
    grid.appendChild(block);
  }
  view.appendChild(grid);
}

function renderRankings(view) {
  view.appendChild(sectionHead("Power Rankings", DATA.weekLabel));
  const card = el("div", "card");
  for (const row of DATA.rankings || []) {
    const t = team(row.teamId);
    const r = el("button", "rank-row row-link");
    r.type = "button";
    r.addEventListener("click", () => openTeam(row.teamId));
    r.style.setProperty("--rail", railColor(t.abbr));
    r.appendChild(el("div", "rank-num", String(row.rank)));
    r.appendChild(logoImg(t.abbr));
    const who = el("div", "rank-team");
    who.appendChild(el("span", "nick", t.nick));
    who.appendChild(el("span", "sub", `${record(row.teamId)}${t.owner ? " · " + t.owner : ""}`));
    r.appendChild(who);
    const d = row.delta;
    const delta = el("span", "delta " + (d > 0 ? "up" : d < 0 ? "down" : "flat"), d > 0 ? `▲ ${d}` : d < 0 ? `▼ ${Math.abs(d)}` : "—");
    r.appendChild(delta);
    card.appendChild(r);
  }
  view.appendChild(card);
}

function renderLeaders(view) {
  const boards = DATA.leaders || [];
  if (!boards.length) { view.appendChild(el("div", "empty", "No stats yet this season.")); return; }
  const grid = el("div", "grid leaders-grid");
  for (const board of boards) {
    const card = el("div", "card leader-card");
    card.appendChild(el("div", "leader-head", board.label));
    const [top, ...others] = board.rows;

    const topRow = el("div", "leader-top");
    topRow.appendChild(avatar(top));
    const who = el("div", "who");
    who.appendChild(el("div", "name", top.name));
    who.appendChild(el("div", "sub", `${top.position} · ${team(top.teamId).nick}`));
    topRow.appendChild(who);
    const val = el("div", "val", top.value.toLocaleString());
    val.appendChild(el("small", null, board.unit));
    topRow.appendChild(val);
    card.appendChild(topRow);

    others.forEach((row, i) => {
      const r = el("div", "leader-row");
      r.appendChild(el("span", "pos-num", String(i + 2)));
      r.appendChild(avatar(row));
      r.appendChild(el("span", "name", row.name));
      r.appendChild(el("span", "sub", team(row.teamId).abbr));
      r.appendChild(el("span", "val", row.value.toLocaleString()));
      card.appendChild(r);
    });
    grid.appendChild(card);
  }
  view.appendChild(grid);
}

const PERSONA_COLORS = ["#1d9bf0", "#e0245e", "#794bc4", "#17bf63"];

function personaColor(handle) {
  let h = 0;
  for (const ch of handle) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  return PERSONA_COLORS[h % PERSONA_COLORS.length];
}

function newsCard(post) {
  const card = el("div", "card post");
  const head = el("div", "post-head");
  const initialsAv = () => {
    const d = el("div", "post-avatar");
    d.style.background = personaColor(post.handle);
    d.textContent = post.name.split(" ").map((w) => w[0] || "").join("").slice(0, 2).toUpperCase();
    return d;
  };
  let av;
  if (post.avatarUrl) {
    av = el("img", "post-avatar");
    av.src = post.avatarUrl;
    av.alt = post.name;
    av.loading = "lazy";
    av.onerror = () => av.replaceWith(initialsAv());
  } else {
    av = initialsAv();
  }
  head.appendChild(av);
  const who = el("div", "post-who");
  const nameLine = el("div", "post-name", post.name);
  nameLine.appendChild(svgIcon("M12 1.7l2.4 2.3 3.3-.6.6 3.3 3 1.6-1.5 3 1.5 3-3 1.6-.6 3.3-3.3-.6-2.4 2.3-2.4-2.3-3.3.6-.6-3.3-3-1.6 1.5-3-1.5-3 3-1.6.6-3.3 3.3.6zM10.7 14.9l5.2-5.2-1.2-1.2-4 4-1.7-1.7-1.2 1.2z", "verified"));
  who.appendChild(nameLine);
  who.appendChild(el("div", "post-handle", post.handle));
  head.appendChild(who);
  head.appendChild(el("span", "post-time", timeAgo(post.postedAt)));
  card.appendChild(head);
  card.appendChild(el("div", "post-text", post.text));
  return card;
}

function renderNews(view) {
  const posts = DATA.news || [];
  if (!posts.length) { view.appendChild(el("div", "empty", "No league news yet — the insiders post after each advance.")); return; }
  const feed = el("div", "grid feed");
  for (const post of posts) feed.appendChild(newsCard(post));
  view.appendChild(feed);
  view.appendChild(el("div", "news-disclaimer", "League insiders are AI-generated parody personalities built from this league's real synced data. Not real people posting, not real reporting."));
}

/* ---------- Trade builder ----------
   Builds a trade from the rosters already in site.json and encodes it as an
   `FO1.` code — the SAME format src/discord/tradeCode.ts decodes. No server:
   the code is pasted into Discord (/trade import), and Discord supplies the
   identity. Pick values mirror src/discord/draftPickValue.ts's constants. */

const TRADE = {
  a: null, b: null,           // teamIds
  aPlayers: [], bPlayers: [], // rosterIds
  aPicks: [], bPicks: [],     // [round, slotOrNull, yearOffset]
  code: null,                 // generated code, cleared on any edit
};
const tradeSearchQ = { a: "", b: "" }; // transient per-side roster filter, survives re-renders but not reloads

function tradeSaveState() {
  try { localStorage.setItem("trade-draft", JSON.stringify(TRADE)); } catch {}
}
function tradeLoadState() {
  try {
    const saved = JSON.parse(localStorage.getItem("trade-draft") || "null");
    if (saved && typeof saved === "object") Object.assign(TRADE, saved, { code: null });
  } catch {}
}
tradeLoadState();

function base64url(str) {
  return btoa(String.fromCharCode(...new TextEncoder().encode(str)))
    .replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
}

function buildTradeCode() {
  return "FO1." + base64url(JSON.stringify([TRADE.a, TRADE.b, TRADE.aPlayers, TRADE.bPlayers, TRADE.aPicks, TRADE.bPicks]));
}

/* Mirrors computeDraftPickValue in draftPickValue.ts — keep the constants in sync. */
function pickValue(round, slot, yearOffset) {
  const perRound = DATA.picksPerRound || 32;
  const s = Math.min(Math.max(slot == null ? Math.ceil(perRound / 2) : slot, 1), perRound);
  const overall = (round - 1) * perRound + s;
  return Math.round(650 * Math.pow(0.97, overall - 1) * Math.pow(0.85, yearOffset));
}

const YEAR_WORDS = ["this year", "next year", "year after"];
function pickChipLabel(p) {
  const [round, slot, yr] = p;
  return `${round}${["st","nd","rd"][round-1] || "th"} rd${slot ? ` (${round}.${String(slot).padStart(2,"0")})` : ""} · ${YEAR_WORDS[yr]}`;
}

function rosterOf(teamId) { return (DATA.rosters && DATA.rosters[String(teamId)]) || []; }

function sideTotal(teamId, playerIds, picks) {
  const roster = rosterOf(teamId);
  const pv = playerIds.reduce((sum, id) => sum + ((roster.find((p) => p.id === id) || {}).value || 0), 0);
  return pv + picks.reduce((sum, p) => sum + pickValue(p[0], p[1], p[2]), 0);
}

function tradeEdited() { TRADE.code = null; tradeSaveState(); render(); }

function renderTradeSide(container, sideKey) {
  const teamId = TRADE[sideKey];
  const playersKey = sideKey + "Players", picksKey = sideKey + "Picks";
  const t = team(teamId);
  const wrap = el("div", "trade-side");

  const head = el("div", "trade-side-head");
  head.appendChild(logoImg(t.abbr));
  head.appendChild(el("span", "label", `${t.nick} send`));
  head.appendChild(el("span", "side-total", String(sideTotal(teamId, TRADE[playersKey], TRADE[picksKey]))));
  wrap.appendChild(head);

  const chips = el("div", "asset-chips");
  for (const id of TRADE[playersKey]) {
    const p = rosterOf(teamId).find((r) => r.id === id);
    if (!p) continue;
    const chip = el("button", "asset-chip");
    chip.type = "button";
    chip.appendChild(avatar({ name: p.name, teamId, portraitId: p.portraitId }));
    chip.appendChild(el("span", null, p.name));
    chip.appendChild(el("span", "chip-val", String(p.value)));
    chip.appendChild(el("span", "chip-x", "✕"));
    chip.addEventListener("click", () => { TRADE[playersKey] = TRADE[playersKey].filter((x) => x !== id); tradeEdited(); });
    chips.appendChild(chip);
  }
  TRADE[picksKey].forEach((pk, i) => {
    const chip = el("button", "asset-chip");
    chip.type = "button";
    chip.appendChild(el("span", null, "🎟 " + pickChipLabel(pk)));
    chip.appendChild(el("span", "chip-val", String(pickValue(pk[0], pk[1], pk[2]))));
    chip.appendChild(el("span", "chip-x", "✕"));
    chip.addEventListener("click", () => { TRADE[picksKey].splice(i, 1); tradeEdited(); });
    chips.appendChild(chip);
  });
  if (chips.childNodes.length) wrap.appendChild(chips);

  const search = el("input", "roster-search");
  search.type = "search";
  search.placeholder = `Search the ${t.nick} roster…`;
  search.value = tradeSearchQ[sideKey] || "";
  wrap.appendChild(search);

  const listCard = el("div", "card");
  const list = el("div", "roster-list");
  listCard.appendChild(list);
  wrap.appendChild(listCard);

  const renderList = () => {
    const q = search.value.trim().toLowerCase();
    list.replaceChildren();
    const rows = rosterOf(teamId).filter((p) => !q || p.name.toLowerCase().includes(q) || p.pos.toLowerCase() === q);
    for (const p of rows.slice(0, q ? 50 : 200)) {
      const selected = TRADE[playersKey].includes(p.id);
      const item = el("button", "roster-item" + (selected ? " selected" : ""));
      item.type = "button";
      item.appendChild(avatar({ name: p.name, teamId, portraitId: p.portraitId }));
      item.appendChild(el("span", "ri-name", p.name));
      item.appendChild(el("span", "ri-sub", `${p.pos} · ${p.ovr} OVR`));
      item.appendChild(el("span", "ri-val", selected ? "" : String(p.value)));
      if (selected) item.appendChild(el("span", "ri-check", "✓"));
      item.addEventListener("click", () => {
        if (selected) TRADE[playersKey] = TRADE[playersKey].filter((x) => x !== p.id);
        else if (TRADE[playersKey].length < 10) TRADE[playersKey] = [...TRADE[playersKey], p.id];
        tradeEdited();
      });
      list.appendChild(item);
    }
    if (!rows.length) list.appendChild(el("div", "empty", "No players match."));
  };
  search.addEventListener("input", () => { tradeSearchQ[sideKey] = search.value; renderList(); });
  renderList();

  const adder = el("div", "pick-adder");
  const roundSel = el("select");
  for (let r = 1; r <= 7; r++) roundSel.appendChild(new Option(`Round ${r}`, String(r)));
  const yearSel = el("select");
  YEAR_WORDS.forEach((w, i) => yearSel.appendChild(new Option(w[0].toUpperCase() + w.slice(1), String(i))));
  const addBtn = el("button", "add-pick-btn", "+ Pick");
  addBtn.type = "button";
  addBtn.addEventListener("click", () => {
    if (TRADE[picksKey].length >= 10) return;
    TRADE[picksKey] = [...TRADE[picksKey], [Number(roundSel.value), null, Number(yearSel.value)]];
    tradeEdited();
  });
  adder.appendChild(roundSel);
  adder.appendChild(yearSel);
  adder.appendChild(addBtn);
  wrap.appendChild(adder);

  container.appendChild(wrap);
}

function renderTrade(view) {
  if (!DATA.rosters) {
    view.appendChild(el("div", "empty", "Trade data isn't in this site version yet — it appears after the next league sync."));
    return;
  }
  view.appendChild(sectionHead("Trade Builder", "no login needed"));
  view.appendChild(el("p", "trade-intro", "Build the deal here, then paste the code into Discord — the bot opens it for review and the committee vote. Whoever pastes it is the proposer."));

  const pickers = el("div", "trade-teams");
  for (const key of ["a", "b"]) {
    const sel = el("select", "team-select");
    sel.appendChild(new Option(key === "a" ? "Team A…" : "Team B…", ""));
    for (const t of [...DATA.teams].sort((x, y) => x.nick.localeCompare(y.nick))) {
      const opt = new Option(t.nick, String(t.teamId));
      opt.selected = TRADE[key] === t.teamId;
      sel.appendChild(opt);
    }
    sel.addEventListener("change", () => {
      TRADE[key] = sel.value ? Number(sel.value) : null;
      TRADE[key + "Players"] = [];
      TRADE[key + "Picks"] = [];
      tradeEdited();
    });
    pickers.appendChild(sel);
    if (key === "a") pickers.appendChild(el("div", "swap-glyph", "⇄"));
  }
  view.appendChild(pickers);

  if (!TRADE.a || !TRADE.b) {
    view.appendChild(el("div", "empty", "Pick both teams to start building."));
    return;
  }
  if (TRADE.a === TRADE.b) {
    view.appendChild(el("div", "empty", "Pick two different teams."));
    return;
  }

  const sides = el("div", "grid trade-sides");
  renderTradeSide(sides, "a");
  renderTradeSide(sides, "b");
  view.appendChild(sides);

  const totalA = sideTotal(TRADE.a, TRADE.aPlayers, TRADE.aPicks);
  const totalB = sideTotal(TRADE.b, TRADE.bPlayers, TRADE.bPicks);
  const hasAssets = TRADE.aPlayers.length + TRADE.bPlayers.length + TRADE.aPicks.length + TRADE.bPicks.length > 0;

  const summary = el("div", "trade-summary");
  const totals = el("div", "totals");
  totals.appendChild(el("span", null, `${team(TRADE.a).abbr} ${totalA}`));
  totals.appendChild(el("span", null, `${team(TRADE.b).abbr} ${totalB}`));
  summary.appendChild(totals);
  // Same math as trade.ts's fairnessLine: whoever SENDS more value favors the other side.
  const combined = totalA + totalB;
  const pct = combined > 0 ? (Math.abs(totalA - totalB) / (combined / 2)) * 100 : 0;
  const verdict = !hasAssets ? "Add players or picks to either side." : pct < 10 ? `Roughly even (within ${pct.toFixed(0)}%).` : `Favors ${totalA > totalB ? team(TRADE.b).nick : team(TRADE.a).nick} by ~${pct.toFixed(0)}%.`;
  summary.appendChild(el("div", "fairness", verdict));

  // Direct submission (when the league has the Worker set up) is the primary CTA;
  // the copy-a-code flow stays as the always-available fallback underneath.
  const directAvailable = Boolean(DATA.submitUrl);
  let siteKey = null;
  try { siteKey = localStorage.getItem("site-key"); } catch {}

  if (directAvailable && !siteKey) {
    const keyRow = el("div");
    const keyInput = el("input", "roster-search");
    keyInput.type = "password";
    keyInput.placeholder = "Paste your key from /site-key (one time)";
    keyInput.autocomplete = "off";
    const keyHint = el("div", "trade-code-hint");
    keyHint.append("To submit straight to Discord, run ");
    keyHint.appendChild(el("code", null, "/site-key"));
    keyHint.append(" there once — tapping the link it DMs you sets this up automatically (or paste the key here).");
    keyInput.addEventListener("change", () => {
      const v = keyInput.value.trim();
      if (v.startsWith("FOK1.")) {
        try { localStorage.setItem("site-key", v); } catch {}
        render();
      }
    });
    keyRow.appendChild(keyInput);
    keyRow.appendChild(keyHint);
    summary.appendChild(keyRow);
  }

  if (directAvailable && siteKey) {
    const submitBtn = el("button", "trade-cta", "Submit to League");
    submitBtn.type = "button";
    submitBtn.disabled = !hasAssets;
    const status = el("div", "trade-code-hint");
    submitBtn.addEventListener("click", async () => {
      submitBtn.disabled = true;
      submitBtn.textContent = "Submitting…";
      status.textContent = "";
      try {
        const res = await fetch(DATA.submitUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ key: siteKey, code: buildTradeCode() }),
        });
        const out = await res.json().catch(() => ({}));
        if (res.ok && out.ok) {
          submitBtn.textContent = "Submitted ✓";
          submitBtn.classList.add("copied-flash");
          status.textContent = "Sent to the league — the trade card is posting to Discord now. If something's off with it, the bot will DM you why.";
        } else {
          submitBtn.disabled = false;
          submitBtn.textContent = "Submit to League";
          if (res.status === 403) {
            try { localStorage.removeItem("site-key"); } catch {}
            status.textContent = "Your key was rejected — run /site-key in Discord for a fresh one, then paste it here again.";
            setTimeout(render, 2500);
          } else {
            status.textContent = (out.error || "Couldn't submit right now.") + " You can still use the trade code below.";
          }
        }
      } catch {
        submitBtn.disabled = false;
        submitBtn.textContent = "Submit to League";
        status.textContent = "Couldn't reach the league server — check your connection, or use the trade code below.";
      }
    });
    summary.appendChild(submitBtn);
    summary.appendChild(status);
  }

  const cta = el("button", "trade-cta" + (directAvailable && siteKey ? " trade-cta-secondary" : ""), TRADE.code ? "Copy Again" : "Get Trade Code");
  cta.type = "button";
  cta.disabled = !hasAssets;
  cta.addEventListener("click", async () => {
    TRADE.code = buildTradeCode();
    try { await navigator.clipboard.writeText(TRADE.code); cta.textContent = "Copied!"; cta.classList.add("copied-flash"); } catch {}
    tradeSaveState();
    render();
  });
  summary.appendChild(cta);

  if (TRADE.code) {
    summary.appendChild(el("div", "trade-code-box", TRADE.code));
    const hint = el("div", "trade-code-hint");
    hint.append("Copied. In Discord, run ");
    const cmd = el("code", null, "/trade import");
    hint.appendChild(cmd);
    hint.append(" and paste this as the code. The bot opens the trade for review — Evaluate, then Submit to the committee.");
    summary.appendChild(hint);
  }
  view.appendChild(summary);
}

/* ---------- Team page ---------- */

const DEV_ORDER = { "X-Factor": 3, "Superstar": 2, "Star": 1, "Normal": 0 };

function renderTeam(view, teamId) {
  const t = team(teamId);
  const standing = (DATA.standings || []).find((s) => s.teamId === teamId);
  const rankRow = (DATA.rankings || []).find((r) => r.teamId === teamId);
  const roster = (DATA.rosters && DATA.rosters[String(teamId)]) || [];

  const back = el("button", "team-back", "← Back");
  back.type = "button";
  back.addEventListener("click", () => closeTeam(false));
  view.appendChild(back);

  // Hero banner in the team's colors with the oversized watermark
  const hero = el("div", "team-hero");
  hero.style.setProperty("--bb-away", railColor(t.abbr));
  hero.style.setProperty("--bb-home", teamColor(t.abbr));
  hero.appendChild(logoImg(t.abbr, "wm wm-away"));
  const head = el("div", "team-hero-head");
  head.appendChild(logoImg(t.abbr, "team-hero-logo"));
  const who = el("div");
  who.appendChild(el("div", "team-hero-city", (t.city || "").toUpperCase()));
  who.appendChild(el("div", "team-hero-nick", t.nick.toUpperCase()));
  const bits = [record(teamId), t.division, t.owner ? "Owner: " + t.owner : null].filter(Boolean).join(" · ");
  who.appendChild(el("div", "team-hero-sub", bits));
  head.appendChild(who);
  hero.appendChild(head);
  view.appendChild(hero);

  // Stat chips
  const chips = el("div", "team-chips");
  const chip = (label, value) => {
    const d = el("div", "team-chip");
    d.appendChild(el("div", "team-chip-val", String(value)));
    d.appendChild(el("div", "team-chip-label", label));
    return d;
  };
  chips.appendChild(chip("Team OVR", t.ovr));
  if (rankRow) chips.appendChild(chip("Power Rank", "#" + rankRow.rank));
  if (standing) {
    chips.appendChild(chip("PF (per gm)", standing.ptsFor));
    chips.appendChild(chip("PA (per gm)", standing.ptsAgainst));
    if (standing.offYdsRank) chips.appendChild(chip("Off Yds Rank", "#" + standing.offYdsRank));
    if (standing.defYdsRank) chips.appendChild(chip("Def Yds Rank", "#" + standing.defYdsRank));
  }
  if (t.gotwCount) chips.appendChild(chip("GOTW Features", t.gotwCount + "x"));
  view.appendChild(chips);

  // CSV export — real static files written at publish time; `download` names the save
  const exports = el("div", "team-exports");
  const csvBtn = el("a", "trade-cta csv-btn", "⬇ Export Roster CSV");
  csvBtn.href = "csv/team-" + teamId + ".csv";
  csvBtn.setAttribute("download", (t.nick || "team") + "-roster.csv");
  exports.appendChild(csvBtn);
  const allBtn = el("a", "csv-all-link", "or download every player in the league (CSV)");
  allBtn.href = "csv/all-players.csv";
  allBtn.setAttribute("download", "all-players.csv");
  exports.appendChild(allBtn);
  view.appendChild(exports);

  // Season results — this team's game log from the recorded history
  const log = [];
  for (const w of DATA.history || []) {
    for (const g of w.games) {
      if (g.kind === "played" && (g.awayTeamId === teamId || g.homeTeamId === teamId)) {
        const home = g.homeTeamId === teamId;
        const oppId = home ? g.awayTeamId : g.homeTeamId;
        const my = home ? g.homeScore : g.awayScore, their = home ? g.awayScore : g.homeScore;
        log.push({ label: w.label, opp: team(oppId), home, result: my > their ? "W" : my < their ? "L" : "T", score: `${my}-${their}` });
      } else if (g.kind === "forceWin" && (g.winnerTeamId === teamId || g.loserTeamId === teamId)) {
        log.push({ label: w.label, opp: team(g.winnerTeamId === teamId ? g.loserTeamId : g.winnerTeamId), home: null, result: g.winnerTeamId === teamId ? "W" : "L", score: "Force Win" });
      } else if (g.kind === "fairSim" && (g.awayTeamId === teamId || g.homeTeamId === teamId)) {
        log.push({ label: w.label, opp: team(g.awayTeamId === teamId ? g.homeTeamId : g.awayTeamId), home: g.homeTeamId === teamId, result: "—", score: "Fair Sim" });
      }
    }
  }
  if (log.length) {
    view.appendChild(sectionHead("Season Results", log.length + " games"));
    const logCard = el("div", "card");
    for (const row of log) {
      const r = el("div", "gamelog-row");
      r.appendChild(el("span", "gamelog-week", row.label.replace("Preseason ", "P").replace("Week ", "W")));
      r.appendChild(el("span", "wl-badge wl-" + row.result.toLowerCase().replace("—", "t"), row.result));
      r.appendChild(logoImg(row.opp.abbr, "hist-logo"));
      r.appendChild(el("span", "gamelog-opp", (row.home === null ? "" : row.home ? "vs " : "@ ") + row.opp.nick));
      r.appendChild(el("span", "gamelog-score", row.score));
      logCard.appendChild(r);
    }
    view.appendChild(logCard);
  }

  // Sortable roster table
  view.appendChild(sectionHead("Roster", roster.length + " players"));
  if (!roster.length) { view.appendChild(el("div", "empty", "No roster data — appears after the next sync.")); return; }

  const wrap = el("div", "card table-wrap");
  const table = el("table", "roster-table");
  const thead = el("thead");
  const headRow = el("tr");
  const cols = [
    { key: "name", label: "Player", sort: (p) => p.name },
    { key: "pos", label: "POS", sort: (p) => p.pos },
    { key: "ovr", label: "OVR", sort: (p) => p.ovr },
    { key: "dev", label: "DEV", sort: (p) => DEV_ORDER[p.dev] ?? -1 },
    { key: "age", label: "AGE", sort: (p) => p.age },
    { key: "value", label: "VALUE", sort: (p) => p.value },
  ];
  for (const col of cols) {
    const th = el("th", teamSort.col === col.key ? "sorted" : "");
    th.textContent = col.label + (teamSort.col === col.key ? (teamSort.dir === -1 ? " ▾" : " ▴") : "");
    th.addEventListener("click", () => {
      if (teamSort.col === col.key) teamSort.dir *= -1;
      else { teamSort.col = col.key; teamSort.dir = col.key === "name" || col.key === "pos" ? 1 : -1; }
      render();
    });
    headRow.appendChild(th);
  }
  thead.appendChild(headRow);
  table.appendChild(thead);

  const colDef = cols.find((col) => col.key === teamSort.col) || cols[2];
  const sorted = roster.slice().sort((a, b) => {
    const va = colDef.sort(a), vb = colDef.sort(b);
    return (va < vb ? -1 : va > vb ? 1 : 0) * teamSort.dir;
  });

  const tbody = el("tbody");
  for (const p of sorted) {
    const tr = el("tr");
    const nameTd = el("td", "rt-name");
    nameTd.appendChild(avatar({ name: p.name, teamId, portraitId: p.portraitId }));
    nameTd.appendChild(el("span", null, p.name));
    tr.appendChild(nameTd);
    tr.appendChild(el("td", null, p.pos));
    tr.appendChild(el("td", "rt-num", String(p.ovr)));
    const devTd = el("td");
    devTd.appendChild(el("span", "dev-badge dev-" + (p.dev || "Normal").toLowerCase().replace(/[^a-z]/g, ""), p.dev || "—"));
    tr.appendChild(devTd);
    tr.appendChild(el("td", "rt-num", String(p.age ?? "—")));
    tr.appendChild(el("td", "rt-num", p.value.toLocaleString()));
    tbody.appendChild(tr);
  }
  table.appendChild(tbody);
  wrap.appendChild(table);
  view.appendChild(wrap);
  view.appendChild(el("div", "news-disclaimer", "Full attributes, contracts, and every rating are in the CSV export above."));
}

/* ---------- Teams directory ---------- */

function renderTeams(view) {
  view.appendChild(sectionHead("Teams", "tap a team for roster, results & CSV"));
  const grid = el("div", "teams-grid");
  const sorted = [...(DATA.teams || [])].sort((a, b) => a.nick.localeCompare(b.nick));
  for (const t of sorted) {
    const card = el("button", "team-card");
    card.type = "button";
    card.style.setProperty("--tc", railColor(t.abbr));
    card.addEventListener("click", () => openTeam(t.teamId));
    card.appendChild(logoImg(t.abbr, "team-card-logo"));
    card.appendChild(el("div", "team-card-nick", t.nick));
    card.appendChild(el("div", "team-card-sub", `${record(t.teamId) || "—"}${t.owner ? " · " + t.owner : ""}`));
    grid.appendChild(card);
  }
  view.appendChild(grid);
}

/* ---------- Player lookup ---------- */

const playerSearch = { q: "", pos: "" }; // transient, survives re-renders
const POS_FILTERS = ["QB", "HB", "WR", "TE", "OL", "EDGE", "DT", "LB", "CB", "S", "K/P"];
const POS_GROUPS = {
  OL: ["LT", "LG", "C", "RG", "RT", "LS"],
  EDGE: ["LEDG", "REDG"],
  LB: ["MIKE", "WILL", "SAM"],
  S: ["SS", "FS"],
  "K/P": ["K", "P"],
};

function renderPlayers(view) {
  view.appendChild(sectionHead("Players", "every rostered player in the league"));

  const search = el("input", "roster-search");
  search.type = "search";
  search.placeholder = "Search by name…";
  search.value = playerSearch.q;
  search.addEventListener("input", () => { playerSearch.q = search.value; renderResults(); });
  view.appendChild(search);

  const pills = el("div", "week-pills");
  for (const pos of POS_FILTERS) {
    const pill = el("button", "week-pill" + (playerSearch.pos === pos ? " active" : ""), pos);
    pill.type = "button";
    pill.addEventListener("click", () => {
      playerSearch.pos = playerSearch.pos === pos ? "" : pos;
      render();
    });
    pills.appendChild(pill);
  }
  view.appendChild(pills);

  const card = el("div", "card");
  const list = el("div");
  card.appendChild(list);
  view.appendChild(card);
  const foot = el("div", "news-disclaimer");
  view.appendChild(foot);

  function matchesPos(p) {
    if (!playerSearch.pos) return true;
    const group = POS_GROUPS[playerSearch.pos];
    return group ? group.includes(p.pos) : p.pos === playerSearch.pos;
  }

  function renderResults() {
    const q = playerSearch.q.trim().toLowerCase();
    const rows = [];
    for (const [teamId, roster] of Object.entries(DATA.rosters || {})) {
      for (const p of roster) {
        if (!matchesPos(p)) continue;
        if (q && !p.name.toLowerCase().includes(q)) continue;
        rows.push({ ...p, teamId: Number(teamId) });
      }
    }
    rows.sort((a, b) => b.ovr - a.ovr || b.value - a.value);
    const shown = rows.slice(0, 50);
    list.replaceChildren();
    for (const p of shown) {
      const r = el("button", "player-row");
      r.type = "button";
      r.addEventListener("click", () => openTeam(p.teamId));
      r.appendChild(avatar({ name: p.name, teamId: p.teamId, portraitId: p.portraitId }));
      const who = el("div", "wire-who");
      who.appendChild(el("div", "wire-name", p.name));
      who.appendChild(el("div", "wire-sub", `${p.pos} · ${team(p.teamId).nick} · ${p.age} yrs`));
      r.appendChild(who);
      const devWrap = el("span", "player-dev");
      devWrap.appendChild(el("span", "dev-badge dev-" + (p.dev || "Normal").toLowerCase().replace(/[^a-z]/g, ""), p.dev || "—"));
      r.appendChild(devWrap);
      r.appendChild(el("span", "player-ovr", String(p.ovr)));
      list.appendChild(r);
    }
    if (!shown.length) list.appendChild(el("div", "empty", "No players match."));
    foot.textContent = rows.length > 50 ? `Showing the top 50 of ${rows.length} matches — narrow the search or tap a position.` : "Tap a player to open their team page. Full attributes are in the team CSV export.";
  }
  renderResults();
}

/* ---------- App shell ---------- */

const RENDERERS = { home: renderHome, teams: renderTeams, players: renderPlayers, standings: renderStandings, rankings: renderRankings, leaders: renderLeaders, news: renderNews, trade: renderTrade };
let activeTab = "home";
let lastRenderedTab = null;
let viewTeamId = null; // non-null = the team detail page is open over the current tab
const teamSort = { col: "ovr", dir: -1 }; // roster table sort state, survives re-renders
let scoreWeek = null; // "stage-week" key of a past week being browsed on Home, null = current week
let expandedGame = null; // scheduleId of the game card expanded into its matchup panel

function openTeam(teamId) {
  viewTeamId = teamId;
  try { history.pushState({ team: teamId }, "", "#team-" + teamId); } catch {}
  render();
}
function closeTeam(viaHistory) {
  viewTeamId = null;
  if (!viaHistory) { try { history.pushState(null, "", location.pathname + location.search); } catch {} }
  render();
}
window.addEventListener("popstate", () => {
  const m = (location.hash || "").match(/^#team-(\d+)$/);
  viewTeamId = m ? Number(m[1]) : null;
  render();
});

function render() {
  const view = document.getElementById("view");
  const keepScroll = lastRenderedTab === activeTab;
  const y = window.scrollY;
  view.replaceChildren();
  if (!DATA) { view.appendChild(el("div", "loading", "Loading league data…")); return; }
  if (viewTeamId != null) { renderTeam(view, viewTeamId); lastRenderedTab = "team-" + viewTeamId; window.scrollTo(0, keepScroll ? y : 0); return; }
  RENDERERS[activeTab](view);
  lastRenderedTab = activeTab;
  // Re-rendering the SAME tab (the trade builder does this on every tap) keeps the
  // scroll position; switching tabs starts at the top like a page change should.
  window.scrollTo(0, keepScroll ? y : 0);
}

for (const btn of document.querySelectorAll(".tab")) {
  btn.addEventListener("click", () => {
    viewTeamId = null;
    try { history.replaceState(null, "", location.pathname + location.search); } catch {}
    activeTab = btn.dataset.tab;
    for (const b of document.querySelectorAll(".tab")) {
      b.classList.toggle("active", b === btn);
      b.setAttribute("aria-selected", String(b === btn));
    }
    render();
  });
}

async function load() {
  try {
    const res = await fetch("site.json", { cache: "no-cache" });
    DATA = await res.json();
  } catch {
    // Offline / fetch failed — the SW may still have served a cached copy via the
    // fetch handler; if not, show the shell's empty state.
    if (!DATA) {
      document.getElementById("view").replaceChildren(el("div", "empty", "Can't reach the league right now — try again when you're back online."));
      return;
    }
  }
  teamIndex.clear();
  for (const t of DATA.teams || []) teamIndex.set(t.teamId, t);
  document.getElementById("week-chip").textContent = DATA.weekLabel || "—";
  const m = (location.hash || "").match(/^#team-(\d+)$/);
  if (m) viewTeamId = Number(m[1]);
  render();
}

/* Magic-link setup: /site-key DMs a personal link ending in #k=FOK1... — tapping
   it lands here, we store the key and scrub it from the URL immediately. The
   fragment never reaches any server (fragments aren't sent in requests), so the
   key exists only in the DM and this device. */
(function keyFromLink() {
  const m = (location.hash || "").match(/[#&]k=(FOK1\.[0-9]+\.[A-Za-z0-9_-]+)/);
  if (!m) return;
  try { localStorage.setItem("site-key", m[1]); } catch {}
  history.replaceState(null, "", location.pathname + location.search);
})();

/* iOS install hint — Safari has no install prompt, so surface the one-time how-to. */
(function iosHint() {
  const isIos = /iphone|ipad|ipod/i.test(navigator.userAgent);
  const standalone = window.matchMedia("(display-mode: standalone)").matches || window.navigator.standalone === true;
  let dismissed = false;
  try { dismissed = localStorage.getItem("ios-hint-dismissed") === "1"; } catch {}
  if (isIos && !standalone && !dismissed) {
    const hint = document.getElementById("ios-hint");
    hint.hidden = false;
    document.getElementById("ios-hint-close").addEventListener("click", () => {
      hint.hidden = true;
      try { localStorage.setItem("ios-hint-dismissed", "1"); } catch {}
    });
  }
})();

if ("serviceWorker" in navigator) {
  navigator.serviceWorker.register("sw.js").catch(() => {});
}

load();
