/* The Front Office — league PWA client.
   Renders site.json (regenerated by the bot at every sync) into the five tabs.
   No framework, no build step — this file IS the app. */

"use strict";

/* Real NFL team palettes keyed by EA's abbrName (note EA quirks: AZ not ARI).
   primary = the brand color used for rails/rings; text stays theme-controlled. */
const TEAM_COLORS = {
  AZ:  { primary: "#97233F", secondary: "#FFB612" },
  ATL: { primary: "#A71930", secondary: "#000000" },
  BAL: { primary: "#241773", secondary: "#9E7C0C" },
  BUF: { primary: "#00338D", secondary: "#C60C30" },
  CAR: { primary: "#0085CA", secondary: "#101820" },
  CHI: { primary: "#0B162A", secondary: "#C83803" },
  CIN: { primary: "#FB4F14", secondary: "#000000" },
  CLE: { primary: "#311D00", secondary: "#FF3C00" },
  DAL: { primary: "#003594", secondary: "#869397" },
  DEN: { primary: "#FB4F14", secondary: "#002244" },
  DET: { primary: "#0076B6", secondary: "#B0B7BC" },
  GB:  { primary: "#203731", secondary: "#FFB612" },
  HOU: { primary: "#03202F", secondary: "#A71930" },
  IND: { primary: "#002C5F", secondary: "#A2AAAD" },
  JAX: { primary: "#006778", secondary: "#D7A22A" },
  KC:  { primary: "#E31837", secondary: "#FFB81C" },
  LAC: { primary: "#0080C6", secondary: "#FFC20E" },
  LAR: { primary: "#003594", secondary: "#FFA300" },
  LV:  { primary: "#000000", secondary: "#A5ACAF" },
  MIA: { primary: "#008E97", secondary: "#FC4C02" },
  MIN: { primary: "#4F2683", secondary: "#FFC62F" },
  NE:  { primary: "#002244", secondary: "#C60C30" },
  NO:  { primary: "#D3BC8D", secondary: "#101820" },
  NYG: { primary: "#0B2265", secondary: "#A71930" },
  NYJ: { primary: "#125740", secondary: "#000000" },
  PHI: { primary: "#004C54", secondary: "#A5ACAF" },
  PIT: { primary: "#FFB612", secondary: "#101820" },
  SEA: { primary: "#002244", secondary: "#69BE28" },
  SF:  { primary: "#AA0000", secondary: "#B3995D" },
  TB:  { primary: "#D50A0A", secondary: "#34302B" },
  TEN: { primary: "#0C2340", secondary: "#4B92DB" },
  WAS: { primary: "#5A1414", secondary: "#FFB612" },
};

/* ESPN logo slugs, where they differ from lowercase EA abbr. */
const LOGO_SLUGS = { AZ: "ari", WAS: "wsh" };

function logoUrl(abbr) {
  const slug = LOGO_SLUGS[abbr] || abbr.toLowerCase();
  return `https://a.espncdn.com/i/teamlogos/nfl/500/${slug}.png`;
}

function portraitUrl(portraitId) {
  return `https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/${portraitId}.png?im=FaceCrop,padding=0.7`;
}

function teamColor(abbr) {
  return (TEAM_COLORS[abbr] || { primary: "#5c6b7d", secondary: "#93a1b3" }).primary;
}

/* A primary that's too dark to read as a rail on the dark theme gets its
   secondary instead (Bears navy, Raiders black, Texans navy...). */
function railColor(abbr) {
  const c = TEAM_COLORS[abbr];
  if (!c) return "#5c6b7d";
  return luminance(c.primary) < 0.05 ? c.secondary : c.primary;
}

function luminance(hex) {
  const n = parseInt(hex.slice(1), 16);
  const r = (n >> 16) / 255, g = ((n >> 8) & 255) / 255, b = (n & 255) / 255;
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/* ---------- State ---------- */

let DATA = null;
const teamIndex = new Map();

function team(id) { return teamIndex.get(id) || { abbr: "?", nick: "Unknown", city: "", division: "" }; }

function record(teamId) {
  const s = (DATA.standings || []).find((r) => r.teamId === teamId);
  if (!s) return "";
  return s.ties ? `${s.wins}-${s.losses}-${s.ties}` : `${s.wins}-${s.losses}`;
}

/* ---------- Tiny DOM helpers ---------- */

function el(tag, cls, text) {
  const node = document.createElement(tag);
  if (cls) node.className = cls;
  if (text !== undefined) node.textContent = text;
  return node;
}

function svgIcon(path, cls) {
  const s = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  s.setAttribute("viewBox", "0 0 24 24");
  if (cls) s.setAttribute("class", cls);
  const p = document.createElementNS("http://www.w3.org/2000/svg", "path");
  p.setAttribute("d", path);
  s.appendChild(p);
  return s;
}

function logoImg(abbr, cls) {
  const img = el("img", cls || "logo");
  img.src = logoUrl(abbr);
  img.alt = abbr;
  img.loading = "lazy";
  img.onerror = () => { img.style.visibility = "hidden"; };
  return img;
}

function avatar(row, sizeCls) {
  const ring = teamColor(team(row.teamId).abbr);
  if (row.portraitId) {
    const img = el("img", "avatar " + (sizeCls || ""));
    img.style.setProperty("--ring", ring);
    img.src = portraitUrl(row.portraitId);
    img.alt = row.name;
    img.loading = "lazy";
    img.onerror = () => img.replaceWith(initialsAvatar(row, ring, sizeCls));
    return img;
  }
  return initialsAvatar(row, ring, sizeCls);
}

function initialsAvatar(row, ring, sizeCls) {
  const d = el("div", "avatar initials " + (sizeCls || ""));
  d.style.setProperty("--ring", ring);
  d.textContent = row.name.split(" ").map((w) => w[0] || "").join("").slice(0, 2).toUpperCase();
  return d;
}

function sectionHead(title, sub) {
  const head = el("div", "section-head");
  head.appendChild(el("div", "section-title", title));
  if (sub) head.appendChild(el("div", "section-sub", sub));
  return head;
}

function timeAgo(iso) {
  const mins = Math.max(1, Math.round((Date.now() - new Date(iso).getTime()) / 60000));
  if (mins < 60) return `${mins}m`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs}h`;
  return `${Math.round(hrs / 24)}d`;
}

/* ---------- Game card ---------- */

const DISCORD_PATH = "M20.3 4.4A19.8 19.8 0 0 0 15.4 3l-.6 1.2a18 18 0 0 0-5.5 0L8.6 3a19.8 19.8 0 0 0-4.9 1.5A20.4 20.4 0 0 0 .2 18.1a19.9 19.9 0 0 0 6 3l1.2-2a12.9 12.9 0 0 1-2-.9l.5-.4a14.2 14.2 0 0 0 12.2 0l.5.4a12.9 12.9 0 0 1-2 .9l1.2 2a19.9 19.9 0 0 0 6-3A20.4 20.4 0 0 0 20.3 4.4ZM8 14.7c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Zm8 0c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Z";

function gameCard(g) {
  const isLink = Boolean(g.channelUrl);
  const card = el(isLink ? "a" : "div", "card" + (g.isGotw ? " gotw" : ""));
  if (isLink) { card.href = g.channelUrl; card.target = "_blank"; card.rel = "noopener"; }

  if (g.isGotw) {
    const eyebrow = el("div", "gotw-eyebrow");
    eyebrow.appendChild(svgIcon("M12 2l2.4 4.9 5.4.8-3.9 3.8.9 5.4L12 14.3 7.2 16.9l.9-5.4L4.2 7.7l5.4-.8z"));
    eyebrow.appendChild(document.createTextNode("Game of the Week"));
    card.appendChild(eyebrow);
  }

  const away = team(g.awayTeamId), home = team(g.homeTeamId);
  const body = el("div", "game");
  body.style.setProperty("--rail", `linear-gradient(to bottom, ${railColor(away.abbr)} 0%, ${railColor(away.abbr)} 48%, ${railColor(home.abbr)} 52%, ${railColor(home.abbr)} 100%)`);

  const decidedByForce = g.forced === "forceWin";
  const awayWon = decidedByForce ? g.forcedWinnerTeamId === g.awayTeamId : g.played && g.awayScore > g.homeScore;
  const homeWon = decidedByForce ? g.forcedWinnerTeamId === g.homeTeamId : g.played && g.homeScore > g.awayScore;
  const decided = g.played || decidedByForce || g.forced === "fairSim";

  for (const [t, score, won] of [[away, g.awayScore, awayWon], [home, g.homeScore, homeWon]]) {
    const row = el("div", "game-row" + (decided && !won && (awayWon || homeWon) ? " loser" : ""));
    row.appendChild(logoImg(t.abbr));
    const name = el("div", "team-name");
    name.appendChild(el("span", "nick", t.nick));
    const rec = record(t.teamId);
    if (rec) name.appendChild(el("span", "record", rec));
    row.appendChild(name);
    row.appendChild(el("span", "score", g.played ? String(score) : "—"));
    if (won) row.appendChild(el("span", "winner-tick"));
    body.appendChild(row);
  }

  const meta = el("div", "game-meta");
  if (g.forced === "forceWin") meta.appendChild(el("span", "chip forced", "Force Win"));
  else if (g.forced === "fairSim") meta.appendChild(el("span", "chip fairsim", "Fair Sim"));
  else if (g.played) meta.appendChild(el("span", "chip final", "Final"));
  else meta.appendChild(el("span", "chip live", "Scheduled"));
  if (isLink) {
    const link = el("span", "discord-link");
    link.appendChild(svgIcon(DISCORD_PATH));
    link.appendChild(document.createTextNode("Game channel"));
    meta.appendChild(link);
  }
  body.appendChild(meta);
  card.appendChild(body);
  return card;
}

/* ---------- Tabs ---------- */

/* The ESPN-style scoreboard rail: one compact chip per game, horizontally
   scrollable, finals first (that's what people check the strip for). */
function scoreStrip(games) {
  const strip = el("div", "scorestrip");
  const ordered = games.slice().sort((a, b) => Number(b.played) - Number(a.played));
  for (const g of ordered) {
    const away = team(g.awayTeamId), home = team(g.homeTeamId);
    const chip = el(g.channelUrl ? "a" : "div", "scorechip");
    if (g.channelUrl) { chip.href = g.channelUrl; chip.target = "_blank"; chip.rel = "noopener"; }
    const decided = g.played;
    for (const [t, score, won] of [[away, g.awayScore, decided && g.awayScore > g.homeScore], [home, g.homeScore, decided && g.homeScore > g.awayScore]]) {
      const row = el("div", "sc-row" + (decided && !won ? " loser" : ""));
      row.appendChild(logoImg(t.abbr, "sc-logo"));
      row.appendChild(el("span", null, t.abbr));
      row.appendChild(el("span", "sc-score", decided ? String(score) : record(t.teamId)));
      chip.appendChild(row);
    }
    const status = g.isGotw ? "★ GOTW" : g.forced === "forceWin" ? "Force Win" : g.forced === "fairSim" ? "Fair Sim" : g.played ? "Final" : "Scheduled";
    chip.appendChild(el("div", "sc-status" + (g.isGotw ? " gotw" : g.played ? " final" : ""), status));
    strip.appendChild(chip);
  }
  return strip;
}

function renderHome(view) {
  const games = (DATA.week.games || []).slice();
  const gotw = games.filter((g) => g.isGotw);
  const rest = games.filter((g) => !g.isGotw);

  if (games.length) view.appendChild(scoreStrip(games));

  if (gotw.length) {
    view.appendChild(sectionHead("Spotlight", DATA.week.label));
    for (const g of gotw) view.appendChild(gameCard(g));
  }
  view.appendChild(sectionHead(gotw.length ? "This Week" : `Games — ${DATA.week.label}`, `${games.length} games`));
  if (!rest.length && !gotw.length) view.appendChild(el("div", "empty", "No games on the schedule yet — check back after the next sync."));
  const grid = el("div", "grid games-grid");
  for (const g of rest) grid.appendChild(gameCard(g));
  view.appendChild(grid);

  if ((DATA.news || []).length) {
    view.appendChild(sectionHead("Latest From The Wire", ""));
    const feed = el("div", "grid feed");
    for (const post of DATA.news.slice(0, 2)) feed.appendChild(newsCard(post));
    view.appendChild(feed);
  }
}

function renderStandings(view) {
  const byDivision = new Map();
  for (const row of DATA.standings || []) {
    if (!byDivision.has(row.division)) byDivision.set(row.division, []);
    byDivision.get(row.division).push(row);
  }
  if (!byDivision.size) { view.appendChild(el("div", "empty", "No standings yet.")); return; }
  const grid = el("div", "grid standings-grid");
  for (const [division, rows] of byDivision) {
    const block = el("div", "division-block");
    block.appendChild(el("div", "division-label", division));
    const card = el("div", "card");
    for (const row of rows) {
      const t = team(row.teamId);
      const r = el("div", "standings-row");
      r.style.setProperty("--rail", railColor(t.abbr));
      r.appendChild(logoImg(t.abbr));
      r.appendChild(el("span", "name", t.nick));
      if (row.streak) {
        const w = row.streak > 0;
        r.appendChild(el("span", "streak " + (w ? "w" : "l"), (w ? "W" : "L") + Math.abs(row.streak)));
      }
      r.appendChild(el("span", "rec", row.ties ? `${row.wins}-${row.losses}-${row.ties}` : `${row.wins}-${row.losses}`));
      r.appendChild(el("span", "pts", `${row.ptsFor} PF · ${row.ptsAgainst} PA`));
      card.appendChild(r);
    }
    block.appendChild(card);
    grid.appendChild(block);
  }
  view.appendChild(grid);
}

function renderRankings(view) {
  view.appendChild(sectionHead("Power Rankings", DATA.weekLabel));
  const card = el("div", "card");
  for (const row of DATA.rankings || []) {
    const t = team(row.teamId);
    const r = el("div", "rank-row");
    r.style.setProperty("--rail", railColor(t.abbr));
    r.appendChild(el("div", "rank-num", String(row.rank)));
    r.appendChild(logoImg(t.abbr));
    const who = el("div", "rank-team");
    who.appendChild(el("span", "nick", t.nick));
    who.appendChild(el("span", "sub", `${record(row.teamId)}${t.owner ? " · " + t.owner : ""}`));
    r.appendChild(who);
    const d = row.delta;
    const delta = el("span", "delta " + (d > 0 ? "up" : d < 0 ? "down" : "flat"), d > 0 ? `▲ ${d}` : d < 0 ? `▼ ${Math.abs(d)}` : "—");
    r.appendChild(delta);
    card.appendChild(r);
  }
  view.appendChild(card);
}

function renderLeaders(view) {
  const boards = DATA.leaders || [];
  if (!boards.length) { view.appendChild(el("div", "empty", "No stats yet this season.")); return; }
  const grid = el("div", "grid leaders-grid");
  for (const board of boards) {
    const card = el("div", "card leader-card");
    card.appendChild(el("div", "leader-head", board.label));
    const [top, ...others] = board.rows;

    const topRow = el("div", "leader-top");
    topRow.appendChild(avatar(top));
    const who = el("div", "who");
    who.appendChild(el("div", "name", top.name));
    who.appendChild(el("div", "sub", `${top.position} · ${team(top.teamId).nick}`));
    topRow.appendChild(who);
    const val = el("div", "val", top.value.toLocaleString());
    val.appendChild(el("small", null, board.unit));
    topRow.appendChild(val);
    card.appendChild(topRow);

    others.forEach((row, i) => {
      const r = el("div", "leader-row");
      r.appendChild(el("span", "pos-num", String(i + 2)));
      r.appendChild(avatar(row));
      r.appendChild(el("span", "name", row.name));
      r.appendChild(el("span", "sub", team(row.teamId).abbr));
      r.appendChild(el("span", "val", row.value.toLocaleString()));
      card.appendChild(r);
    });
    grid.appendChild(card);
  }
  view.appendChild(grid);
}

const PERSONA_COLORS = ["#1d9bf0", "#e0245e", "#794bc4", "#17bf63"];

function personaColor(handle) {
  let h = 0;
  for (const ch of handle) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  return PERSONA_COLORS[h % PERSONA_COLORS.length];
}

function newsCard(post) {
  const card = el("div", "card post");
  const head = el("div", "post-head");
  const av = el("div", "post-avatar");
  av.style.background = personaColor(post.handle);
  av.textContent = post.name.split(" ").map((w) => w[0] || "").join("").slice(0, 2).toUpperCase();
  head.appendChild(av);
  const who = el("div", "post-who");
  const nameLine = el("div", "post-name", post.name);
  nameLine.appendChild(svgIcon("M12 1.7l2.4 2.3 3.3-.6.6 3.3 3 1.6-1.5 3 1.5 3-3 1.6-.6 3.3-3.3-.6-2.4 2.3-2.4-2.3-3.3.6-.6-3.3-3-1.6 1.5-3-1.5-3 3-1.6.6-3.3 3.3.6zM10.7 14.9l5.2-5.2-1.2-1.2-4 4-1.7-1.7-1.2 1.2z", "verified"));
  who.appendChild(nameLine);
  who.appendChild(el("div", "post-handle", post.handle));
  head.appendChild(who);
  head.appendChild(el("span", "post-time", timeAgo(post.postedAt)));
  card.appendChild(head);
  card.appendChild(el("div", "post-text", post.text));
  return card;
}

function renderNews(view) {
  const posts = DATA.news || [];
  if (!posts.length) { view.appendChild(el("div", "empty", "No league news yet — the insiders post after each advance.")); return; }
  const feed = el("div", "grid feed");
  for (const post of posts) feed.appendChild(newsCard(post));
  view.appendChild(feed);
  view.appendChild(el("div", "news-disclaimer", "League insiders are AI personalities generated from this league's real synced data. Not real reporters, not real reporting."));
}

/* ---------- App shell ---------- */

const RENDERERS = { home: renderHome, standings: renderStandings, rankings: renderRankings, leaders: renderLeaders, news: renderNews };
let activeTab = "home";

function render() {
  const view = document.getElementById("view");
  view.replaceChildren();
  if (!DATA) { view.appendChild(el("div", "loading", "Loading league data…")); return; }
  RENDERERS[activeTab](view);
  window.scrollTo(0, 0);
}

for (const btn of document.querySelectorAll(".tab")) {
  btn.addEventListener("click", () => {
    activeTab = btn.dataset.tab;
    for (const b of document.querySelectorAll(".tab")) {
      b.classList.toggle("active", b === btn);
      b.setAttribute("aria-selected", String(b === btn));
    }
    render();
  });
}

async function load() {
  try {
    const res = await fetch("site.json", { cache: "no-cache" });
    DATA = await res.json();
  } catch {
    // Offline / fetch failed — the SW may still have served a cached copy via the
    // fetch handler; if not, show the shell's empty state.
    if (!DATA) {
      document.getElementById("view").replaceChildren(el("div", "empty", "Can't reach the league right now — try again when you're back online."));
      return;
    }
  }
  teamIndex.clear();
  for (const t of DATA.teams || []) teamIndex.set(t.teamId, t);
  document.getElementById("week-chip").textContent = DATA.weekLabel || "—";
  render();
}

/* iOS install hint — Safari has no install prompt, so surface the one-time how-to. */
(function iosHint() {
  const isIos = /iphone|ipad|ipod/i.test(navigator.userAgent);
  const standalone = window.matchMedia("(display-mode: standalone)").matches || window.navigator.standalone === true;
  let dismissed = false;
  try { dismissed = localStorage.getItem("ios-hint-dismissed") === "1"; } catch {}
  if (isIos && !standalone && !dismissed) {
    const hint = document.getElementById("ios-hint");
    hint.hidden = false;
    document.getElementById("ios-hint-close").addEventListener("click", () => {
      hint.hidden = true;
      try { localStorage.setItem("ios-hint-dismissed", "1"); } catch {}
    });
  }
})();

if ("serviceWorker" in navigator) {
  navigator.serviceWorker.register("sw.js").catch(() => {});
}

load();
