/* Bully League — league PWA client.
   Renders site.json (regenerated by the bot at every sync) into the five tabs.
   No framework, no build step — this file IS the app. */

"use strict";

/* Real NFL team palettes keyed by EA's abbrName (note EA quirks: AZ not ARI).
   primary = the brand color used for rails/rings; text stays theme-controlled. */
const TEAM_COLORS = {
  AZ:  { primary: "#97233F", secondary: "#FFB612" },
  ATL: { primary: "#A71930", secondary: "#000000" },
  BAL: { primary: "#241773", secondary: "#9E7C0C" },
  BUF: { primary: "#00338D", secondary: "#C60C30" },
  CAR: { primary: "#0085CA", secondary: "#101820" },
  CHI: { primary: "#0B162A", secondary: "#C83803" },
  CIN: { primary: "#FB4F14", secondary: "#000000" },
  CLE: { primary: "#311D00", secondary: "#FF3C00" },
  DAL: { primary: "#003594", secondary: "#869397" },
  DEN: { primary: "#FB4F14", secondary: "#002244" },
  DET: { primary: "#0076B6", secondary: "#B0B7BC" },
  GB:  { primary: "#203731", secondary: "#FFB612" },
  HOU: { primary: "#03202F", secondary: "#A71930" },
  IND: { primary: "#002C5F", secondary: "#A2AAAD" },
  JAX: { primary: "#006778", secondary: "#D7A22A" },
  KC:  { primary: "#E31837", secondary: "#FFB81C" },
  LAC: { primary: "#0080C6", secondary: "#FFC20E" },
  LAR: { primary: "#003594", secondary: "#FFA300" },
  LV:  { primary: "#000000", secondary: "#A5ACAF" },
  MIA: { primary: "#008E97", secondary: "#FC4C02" },
  MIN: { primary: "#4F2683", secondary: "#FFC62F" },
  NE:  { primary: "#002244", secondary: "#C60C30" },
  NO:  { primary: "#D3BC8D", secondary: "#101820" },
  NYG: { primary: "#0B2265", secondary: "#A71930" },
  NYJ: { primary: "#125740", secondary: "#000000" },
  PHI: { primary: "#004C54", secondary: "#A5ACAF" },
  PIT: { primary: "#FFB612", secondary: "#101820" },
  SEA: { primary: "#002244", secondary: "#69BE28" },
  SF:  { primary: "#AA0000", secondary: "#B3995D" },
  TB:  { primary: "#D50A0A", secondary: "#34302B" },
  TEN: { primary: "#0C2340", secondary: "#4B92DB" },
  WAS: { primary: "#5A1414", secondary: "#FFB612" },
};

/* ESPN logo slugs, where they differ from lowercase EA abbr. */
const LOGO_SLUGS = { AZ: "ari", WAS: "wsh" };

function logoUrl(abbr) {
  const slug = LOGO_SLUGS[abbr] || abbr.toLowerCase();
  return `https://a.espncdn.com/i/teamlogos/nfl/500/${slug}.png`;
}

function portraitUrl(portraitId) {
  return `https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/${portraitId}.png?im=FaceCrop,padding=0.7`;
}

function teamColor(abbr) {
  return (TEAM_COLORS[abbr] || { primary: "#5c6b7d", secondary: "#93a1b3" }).primary;
}

/* A primary that's too dark to read as a rail on the dark theme gets its
   secondary instead (Bears navy, Raiders black, Texans navy...). */
function railColor(abbr) {
  const c = TEAM_COLORS[abbr];
  if (!c) return "#5c6b7d";
  return luminance(c.primary) < 0.05 ? c.secondary : c.primary;
}

function luminance(hex) {
  const n = parseInt(hex.slice(1), 16);
  const r = (n >> 16) / 255, g = ((n >> 8) & 255) / 255, b = (n & 255) / 255;
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/* ---------- State ---------- */

let DATA = null;
const teamIndex = new Map();

function team(id) { return teamIndex.get(id) || { abbr: "?", nick: "Unknown", city: "", division: "" }; }

function record(teamId) {
  const s = (DATA.standings || []).find((r) => r.teamId === teamId);
  if (!s) return "";
  return s.ties ? `${s.wins}-${s.losses}-${s.ties}` : `${s.wins}-${s.losses}`;
}

/* ---------- Tiny DOM helpers ---------- */

function el(tag, cls, text) {
  const node = document.createElement(tag);
  if (cls) node.className = cls;
  if (text !== undefined) node.textContent = text;
  return node;
}

function svgIcon(path, cls) {
  const s = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  s.setAttribute("viewBox", "0 0 24 24");
  if (cls) s.setAttribute("class", cls);
  const p = document.createElementNS("http://www.w3.org/2000/svg", "path");
  p.setAttribute("d", path);
  s.appendChild(p);
  return s;
}

function logoImg(abbr, cls) {
  const img = el("img", cls || "logo");
  img.src = logoUrl(abbr);
  img.alt = abbr;
  img.loading = "lazy";
  img.onerror = () => { img.style.visibility = "hidden"; };
  return img;
}

function avatar(row, sizeCls) {
  const ring = teamColor(team(row.teamId).abbr);
  if (row.portraitId) {
    const img = el("img", "avatar " + (sizeCls || ""));
    img.style.setProperty("--ring", ring);
    img.src = portraitUrl(row.portraitId);
    img.alt = row.name;
    img.loading = "lazy";
    img.onerror = () => img.replaceWith(initialsAvatar(row, ring, sizeCls));
    return img;
  }
  return initialsAvatar(row, ring, sizeCls);
}

function initialsAvatar(row, ring, sizeCls) {
  const d = el("div", "avatar initials " + (sizeCls || ""));
  d.style.setProperty("--ring", ring);
  d.textContent = row.name.split(" ").map((w) => w[0] || "").join("").slice(0, 2).toUpperCase();
  return d;
}

function sectionHead(title, sub) {
  const head = el("div", "section-head");
  head.appendChild(el("div", "section-title", title));
  if (sub) head.appendChild(el("div", "section-sub", sub));
  return head;
}

function timeAgo(iso) {
  const mins = Math.max(1, Math.round((Date.now() - new Date(iso).getTime()) / 60000));
  if (mins < 60) return `${mins}m`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs}h`;
  return `${Math.round(hrs / 24)}d`;
}

/* ---------- Game card ---------- */

const DISCORD_PATH = "M20.3 4.4A19.8 19.8 0 0 0 15.4 3l-.6 1.2a18 18 0 0 0-5.5 0L8.6 3a19.8 19.8 0 0 0-4.9 1.5A20.4 20.4 0 0 0 .2 18.1a19.9 19.9 0 0 0 6 3l1.2-2a12.9 12.9 0 0 1-2-.9l.5-.4a14.2 14.2 0 0 0 12.2 0l.5.4a12.9 12.9 0 0 1-2 .9l1.2 2a19.9 19.9 0 0 0 6-3A20.4 20.4 0 0 0 20.3 4.4ZM8 14.7c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Zm8 0c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Z";

/* ---------- Player card: tap any player anywhere ---------- */

function playerById(id) {
  for (const [teamId, roster] of Object.entries(DATA.rosters || {})) {
    const p = roster.find((x) => x.id === id);
    if (p) return { p, teamId: Number(teamId) };
  }
  const fa = (DATA.freeAgents || []).find((x) => x.id === id);
  if (fa) return { p: fa, teamId: null };
  return null;
}

function fmtMoney(n) {
  if (n == null || !isFinite(n) || n === 0) return null;
  if (Math.abs(n) >= 1e6) return "$" + (n / 1e6).toFixed(1).replace(/\.0$/, "") + "M";
  if (Math.abs(n) >= 1e3) return "$" + Math.round(n / 1e3) + "K";
  return "$" + n;
}

/**
 * The universal player card — a strategy sheet, not a headshot viewer: bio,
 * contract, dev, the season box-score line, position-relevant ratings (all 37
 * on toggle), and — for a free agent while advising as a team — the fit
 * verdict with its reasons. Every field shown is real synced data; sections
 * whose data is missing (older cached site.json) simply don't render.
 */
function openPlayerCard(id) {
  if (!id) return;
  const hit = playerById(id);
  if (!hit) return;
  const { p, teamId } = hit;
  const t = teamId != null ? team(teamId) : null;

  const ov = el("div", "pcard-ov");
  const close = () => {
    ov.remove();
    document.removeEventListener("keydown", onKey);
    document.body.style.overflow = "";
  };
  const onKey = (e) => { if (e.key === "Escape") close(); };
  document.addEventListener("keydown", onKey);
  ov.addEventListener("click", (e) => { if (e.target === ov) close(); });

  const card = el("div", "pcard");
  const x = el("button", "pcard-close", "✕");
  x.type = "button";
  x.setAttribute("aria-label", "Close");
  x.addEventListener("click", close);
  card.appendChild(x);

  const head = el("div", "pcard-head");
  head.appendChild(avatar({ name: p.name, teamId: teamId ?? -1, portraitId: p.portraitId }, "pcard-av"));
  const who = el("div", "pcard-who");
  who.appendChild(el("div", "pcard-name display", p.name));
  const devBadge = el("span", "dev-badge dev-" + (p.dev || "Normal").toLowerCase().replace(/[^a-z]/g, ""), p.dev || "—");
  const sub = el("div", "pcard-sub", [p.pos, `${p.age} yrs`, p.yrs != null ? `${p.yrs} yrs pro` : null].filter(Boolean).join(" · ") + " ");
  sub.appendChild(devBadge);
  who.appendChild(sub);
  const teamLine = el("div", "pcard-team");
  if (t) {
    teamLine.appendChild(logoImg(t.abbr, "pcard-team-logo"));
    teamLine.appendChild(el("span", null, `${t.city} ${t.nick}`));
  } else {
    teamLine.appendChild(el("span", "pcard-fa-pill", "FREE AGENT"));
  }
  who.appendChild(teamLine);
  head.appendChild(who);
  card.appendChild(head);

  const chips = el("div", "team-chips pcard-chips");
  const chip = (label, value) => {
    const d = el("div", "team-chip");
    d.appendChild(el("div", "team-chip-val", String(value)));
    d.appendChild(el("div", "team-chip-label", label));
    return d;
  };
  chips.appendChild(chip("OVR", p.ovr));
  if (p.value != null) chips.appendChild(chip("Trade value", p.value.toLocaleString()));
  if (fmtMoney(p.salary)) chips.appendChild(chip("Salary", fmtMoney(p.salary)));
  if (fmtMoney(p.capHit)) chips.appendChild(chip("Cap hit", fmtMoney(p.capHit)));
  if (p.yrsLeft != null && p.yrsLeft > 0) chips.appendChild(chip("Contract yrs", p.yrsLeft));
  if (p.inj) chips.appendChild(chip("🩹 Out", p.inj + " wks"));
  card.appendChild(chips);

  // Fit advisement — only meaningful for a free agent while a team is picked.
  if (teamId == null && faView.teamId) {
    const fit = fitFor(p, faView.teamId);
    const sec = el("div", "pcard-sec");
    const lbl = el("div", "need-depth-label", `Fit for the ${team(faView.teamId).nick} `);
    lbl.appendChild(el("span", "fit-badge fit-" + fit.verdict.toLowerCase().replace(/[^a-z]/g, ""), fit.verdict));
    sec.appendChild(lbl);
    for (const reason of fit.reasons) sec.appendChild(el("div", "need-reason", "• " + reason));
    card.appendChild(sec);
  }

  const line = (DATA.stats || {})[String(id)];
  const statSec = el("div", "pcard-sec");
  statSec.appendChild(el("div", "need-depth-label", line ? `Season stats · ${line.w} wk` : "Season stats"));
  if (line) {
    const st = (label, txt) => {
      const d = el("div", "pcard-stat");
      d.appendChild(el("strong", null, label));
      d.appendChild(document.createTextNode(" " + txt));
      return d;
    };
    if (line.pass) statSec.appendChild(st("Passing", `${line.pass.cmp}/${line.pass.att} · ${line.pass.yds.toLocaleString()} yds · ${line.pass.td} TD · ${line.pass.int} INT`));
    if (line.rush) statSec.appendChild(st("Rushing", `${line.rush.att} att · ${line.rush.yds.toLocaleString()} yds · ${line.rush.td} TD` + (line.rush.att ? ` · ${(line.rush.yds / line.rush.att).toFixed(1)}/carry` : "")));
    if (line.rec) statSec.appendChild(st("Receiving", `${line.rec.ct} rec · ${line.rec.yds.toLocaleString()} yds · ${line.rec.td} TD · ${line.rec.drp} drops`));
    if (line.def) statSec.appendChild(st("Defense", `${line.def.tkl} tkl · ${line.def.sck} sacks · ${line.def.int} INT · ${line.def.ff} FF`));
    if (line.kick) statSec.appendChild(st("Kicking", `FG ${line.kick.fgm}/${line.kick.fga} · XP ${line.kick.xpm}/${line.kick.xpa}`));
    if (line.punt && line.punt.att) statSec.appendChild(st("Punting", `${line.punt.att} punts · ${(line.punt.yds / line.punt.att).toFixed(1)} avg`));
  } else {
    statSec.appendChild(el("div", "pcard-stat-empty", "No box-score stats recorded this season."));
  }
  card.appendChild(statSec);

  if (p.rat && Object.keys(p.rat).length) {
    const sec = el("div", "pcard-sec");
    const group = POS_TO_GROUP[p.pos] || "";
    let showAllR = false;
    const lbl = el("div", "need-depth-label");
    const grid = el("div", "pcard-ratings");
    const draw = () => {
      lbl.textContent = showAllR ? "All ratings · best first" : "Key ratings" + (group ? ` for ${group}` : "");
      grid.replaceChildren();
      const keys = showAllR
        ? Object.keys(p.rat).sort((a, b) => p.rat[b] - p.rat[a])
        : (GROUP_RATING_COLS[group] || GROUP_RATING_COLS[""]);
      for (const k of keys) {
        const v = p.rat[k];
        if (v == null) continue;
        const cell = el("div", "pcard-rat");
        cell.title = RATING_NAMES[k] || k;
        cell.appendChild(el("div", "pcard-rat-val" + (v >= 90 ? " hi" : v >= 80 ? " good" : v < 70 ? " low" : ""), String(v)));
        cell.appendChild(el("div", "pcard-rat-key", k.toUpperCase()));
        grid.appendChild(cell);
      }
    };
    draw();
    sec.appendChild(lbl);
    sec.appendChild(grid);
    const tog = el("button", "csv-all-link pcard-rat-toggle", "Show all 37 ratings");
    tog.type = "button";
    tog.addEventListener("click", () => { showAllR = !showAllR; tog.textContent = showAllR ? "Show key ratings" : "Show all 37 ratings"; draw(); });
    sec.appendChild(tog);
    card.appendChild(sec);
  }

  if (t) {
    const btn = el("button", "trade-cta pcard-teambtn", `View ${t.nick} team page →`);
    btn.type = "button";
    btn.addEventListener("click", () => { close(); if (viewTeamId !== teamId) openTeam(teamId); });
    card.appendChild(btn);
  }

  ov.appendChild(card);
  document.body.appendChild(ov);
  document.body.style.overflow = "hidden";
}

/* Side-by-side matchup panel (tale of the tape) shown when a game card is tapped. */
function matchupPanel(g, away, home) {
  const panel = el("div", "matchup-panel");
  const sA = (DATA.standings || []).find((s) => s.teamId === g.awayTeamId);
  const sB = (DATA.standings || []).find((s) => s.teamId === g.homeTeamId);
  const rA = (DATA.rankings || []).find((r) => r.teamId === g.awayTeamId);
  const rB = (DATA.rankings || []).find((r) => r.teamId === g.homeTeamId);

  const addTapeRows = (rows) => {
    for (const row of rows) {
      if (row.a === row.b) row.betterA = null;
      const r = el("div", "tape-row");
      r.appendChild(el("span", "tape-val" + (row.betterA === true ? " better" : ""), String(row.a)));
      r.appendChild(el("span", "tape-label", row.label));
      r.appendChild(el("span", "tape-val right" + (row.betterA === false ? " better" : ""), String(row.b)));
      panel.appendChild(r);
    }
  };
  addTapeRows([
    { label: "Record", a: record(g.awayTeamId) || "—", b: record(g.homeTeamId) || "—", betterA: sA && sB ? sA.wins - sA.losses > sB.wins - sB.losses : null },
    { label: "Team OVR", a: away.ovr ?? "—", b: home.ovr ?? "—", betterA: (away.ovr ?? 0) > (home.ovr ?? 0) },
    { label: "Power Rank", a: rA ? "#" + rA.rank : "—", b: rB ? "#" + rB.rank : "—", betterA: rA && rB ? rA.rank < rB.rank : null },
    { label: "PPG", a: sA?.ptsFor ?? "—", b: sB?.ptsFor ?? "—", betterA: (sA?.ptsFor ?? 0) > (sB?.ptsFor ?? 0) },
    { label: "PA/G", a: sA?.ptsAgainst ?? "—", b: sB?.ptsAgainst ?? "—", betterA: (sA?.ptsAgainst ?? 99) < (sB?.ptsAgainst ?? 99) },
  ]);

  // The strategy breakdown, from the tendencies engine: how each identity
  // matches up against the other side's defense, then auto-computed keys.
  const tA = (DATA.tendencies || {})[String(g.awayTeamId)];
  const tB = (DATA.tendencies || {})[String(g.homeTeamId)];
  if (tA && tB) {
    const signed = (n) => (n > 0 ? "+" + n : String(n));
    panel.appendChild(el("div", "tape-section-label", "The Clash"));
    addTapeRows([
      { label: "Run / Pass mix", a: `${tA.runPct}·${100 - tA.runPct}`, b: `${tB.runPct}·${100 - tB.runPct}`, betterA: null },
      { label: "Pass offense", a: "#" + tA.passYdsPgRank, b: "#" + tB.passYdsPgRank, betterA: tA.passYdsPgRank < tB.passYdsPgRank },
      { label: "Rush offense", a: "#" + tA.rushYdsPgRank, b: "#" + tB.rushYdsPgRank, betterA: tA.rushYdsPgRank < tB.rushYdsPgRank },
      { label: "Pass defense", a: "#" + tA.defPassYdsPgRank, b: "#" + tB.defPassYdsPgRank, betterA: tA.defPassYdsPgRank < tB.defPassYdsPgRank },
      { label: "Rush defense", a: "#" + tA.defRushYdsPgRank, b: "#" + tB.defRushYdsPgRank, betterA: tA.defRushYdsPgRank < tB.defRushYdsPgRank },
      { label: "3rd down", a: tA.thirdDownPct + "%", b: tB.thirdDownPct + "%", betterA: tA.thirdDownPct > tB.thirdDownPct },
      { label: "Red zone TD", a: tA.redZoneTdPct + "%", b: tB.redZoneTdPct + "%", betterA: tA.redZoneTdPct > tB.redZoneTdPct },
      { label: "TO margin", a: signed(tA.takeaways - tA.giveaways), b: signed(tB.takeaways - tB.giveaways), betterA: tA.takeaways - tA.giveaways > tB.takeaways - tB.giveaways },
    ]);

    const keys = [];
    // Offense-vs-defense mismatches: a big rank gap is a lane to attack.
    const combos = [
      { atk: away, o: tA.passYdsPgRank, d: tB.defPassYdsPgRank, mode: "air" },
      { atk: away, o: tA.rushYdsPgRank, d: tB.defRushYdsPgRank, mode: "ground" },
      { atk: home, o: tB.passYdsPgRank, d: tA.defPassYdsPgRank, mode: "air" },
      { atk: home, o: tB.rushYdsPgRank, d: tA.defRushYdsPgRank, mode: "ground" },
    ]
      .map((c) => ({ ...c, gap: c.d - c.o }))
      .filter((c) => c.gap >= 6)
      .sort((a, b) => b.gap - a.gap)
      .slice(0, 2);
    for (const c of combos) {
      keys.push(c.mode === "air"
        ? `${c.atk.abbr} can win through the air — #${c.o} pass offense against the #${c.d} pass defense.`
        : `${c.atk.abbr} can win on the ground — #${c.o} rush offense against the #${c.d} rush defense.`);
    }
    // Concentrated weapons are game-planable — name them.
    const weapon = (tend, atk, def) => {
      const w = (tend.targets || [])[0];
      if (w && w.sharePct >= 22) keys.push(`${def.abbr} must account for ${w.name} — ${w.sharePct}% of ${atk.abbr} targets.`);
      const r = (tend.rushers || [])[0];
      if (r && r.sharePct >= 55) keys.push(`${r.name} IS the ${atk.abbr} run game (${r.sharePct}% of carries).`);
    };
    weapon(tA, away, home);
    weapon(tB, home, away);
    if (keys.length) {
      panel.appendChild(el("div", "tape-section-label", "Keys to the game"));
      for (const k of keys.slice(0, 4)) panel.appendChild(el("div", "tape-key", "• " + k));
    }
  }

  // Earlier meeting this season, from the recorded history
  for (const w of DATA.history || []) {
    for (const h of w.games) {
      if (h.kind !== "played") continue;
      const same = (h.awayTeamId === g.awayTeamId && h.homeTeamId === g.homeTeamId) || (h.awayTeamId === g.homeTeamId && h.homeTeamId === g.awayTeamId);
      if (same && !(g.played && h.awayScore === g.awayScore && h.homeScore === g.homeScore && h.awayTeamId === g.awayTeamId)) {
        panel.appendChild(el("div", "tape-h2h", `Earlier this season (${w.label}): ${team(h.awayTeamId).abbr} ${h.awayScore} — ${h.homeScore} ${team(h.homeTeamId).abbr}`));
      }
    }
  }

  if (g.channelUrl && !g.played) {
    const cta = el("a", "matchup-cta", "Open game channel →");
    cta.href = g.channelUrl;
    cta.target = "_blank";
    cta.rel = "noopener";
    cta.addEventListener("click", (e) => e.stopPropagation());
    panel.appendChild(cta);
  }
  return panel;
}

function gameCard(g) {
  const card = el("div", "card game-toggle" + (g.isGotw ? " gotw" : ""));
  card.addEventListener("click", () => {
    expandedGame = expandedGame === g.scheduleId ? null : g.scheduleId;
    render();
  });

  const away = team(g.awayTeamId), home = team(g.homeTeamId);

  if (g.isGotw) {
    const eyebrow = el("div", "gotw-eyebrow");
    eyebrow.appendChild(svgIcon("M12 2l2.4 4.9 5.4.8-3.9 3.8.9 5.4L12 14.3 7.2 16.9l.9-5.4L4.2 7.7l5.4-.8z"));
    eyebrow.appendChild(document.createTextNode("Game of the Week"));
    card.appendChild(eyebrow);

    const billboard = el("div", "gotw-billboard");
    billboard.style.setProperty("--bb-away", railColor(away.abbr));
    billboard.style.setProperty("--bb-home", railColor(home.abbr));
    billboard.appendChild(logoImg(away.abbr, "bb-logo"));
    billboard.appendChild(el("span", "gotw-vs", "VS"));
    billboard.appendChild(logoImg(home.abbr, "bb-logo"));
    card.appendChild(billboard);
  }
  const body = el("div", "game");
  body.style.setProperty("--rail", `linear-gradient(to bottom, ${railColor(away.abbr)} 0%, ${railColor(away.abbr)} 48%, ${railColor(home.abbr)} 52%, ${railColor(home.abbr)} 100%)`);
  body.appendChild(logoImg(home.abbr, "wm"));

  const decidedByForce = g.forced === "forceWin";
  const awayWon = decidedByForce ? g.forcedWinnerTeamId === g.awayTeamId : g.played && g.awayScore > g.homeScore;
  const homeWon = decidedByForce ? g.forcedWinnerTeamId === g.homeTeamId : g.played && g.homeScore > g.awayScore;
  const decided = g.played || decidedByForce || g.forced === "fairSim";

  for (const [t, score, won] of [[away, g.awayScore, awayWon], [home, g.homeScore, homeWon]]) {
    const row = el("div", "game-row" + (decided && !won && (awayWon || homeWon) ? " loser" : ""));
    row.appendChild(logoImg(t.abbr));
    const name = el("div", "team-name");
    name.appendChild(el("span", "nick", t.nick));
    const rec = record(t.teamId);
    if (rec) name.appendChild(el("span", "record", rec));
    row.appendChild(name);
    row.appendChild(el("span", "score", g.played ? String(score) : "—"));
    if (won) row.appendChild(el("span", "winner-tick"));
    body.appendChild(row);
  }

  const meta = el("div", "game-meta");
  if (g.forced === "forceWin") meta.appendChild(el("span", "chip forced", "Force Win"));
  else if (g.forced === "fairSim") meta.appendChild(el("span", "chip fairsim", "Fair Sim"));
  else if (g.played) meta.appendChild(el("span", "chip final", "Final"));
  else meta.appendChild(el("span", "chip live", "Scheduled"));
  meta.appendChild(el("span", "expand-hint", expandedGame === g.scheduleId ? "Hide matchup ▴" : "Matchup ▾"));
  body.appendChild(meta);
  card.appendChild(body);
  if (expandedGame === g.scheduleId) card.appendChild(matchupPanel(g, away, home));
  return card;
}

/* ---------- Tabs ---------- */

/* The ESPN-style scoreboard rail: one compact chip per game, horizontally
   scrollable, finals first (that's what people check the strip for). */
function scoreStrip(games) {
  const strip = el("div", "scorestrip");
  const ordered = games.slice().sort((a, b) => Number(b.played) - Number(a.played));
  for (const g of ordered) {
    const away = team(g.awayTeamId), home = team(g.homeTeamId);
    const chip = el(g.channelUrl ? "a" : "div", "scorechip");
    if (g.channelUrl) { chip.href = g.channelUrl; chip.target = "_blank"; chip.rel = "noopener"; }
    const decided = g.played;
    for (const [t, score, won] of [[away, g.awayScore, decided && g.awayScore > g.homeScore], [home, g.homeScore, decided && g.homeScore > g.awayScore]]) {
      const row = el("div", "sc-row" + (decided && !won ? " loser" : ""));
      row.appendChild(logoImg(t.abbr, "sc-logo"));
      row.appendChild(el("span", null, t.abbr));
      row.appendChild(el("span", "sc-score", decided ? String(score) : record(t.teamId)));
      chip.appendChild(row);
    }
    const status = g.isGotw ? "★ GOTW" : g.forced === "forceWin" ? "Force Win" : g.forced === "fairSim" ? "Fair Sim" : g.played ? "Final" : "Scheduled";
    chip.appendChild(el("div", "sc-status" + (g.isGotw ? " gotw" : g.played ? " final" : ""), status));
    strip.appendChild(chip);
  }
  return strip;
}

/* ---------- Front page (Home) ----------
   ESPN anatomy: score rail on top, a HERO, then a main scoreboard column with a
   right rail of Top Headlines / Injury Report / Transactions (rail stacks under
   on phones). The flash lives in the hero and the rail density, not the chrome. */

function heroCard(g) {
  const away = team(g.awayTeamId), home = team(g.homeTeamId);
  const hero = el(g.channelUrl ? "a" : "div", "hero");
  if (g.channelUrl) { hero.href = g.channelUrl; hero.target = "_blank"; hero.rel = "noopener"; }
  hero.style.setProperty("--bb-away", railColor(away.abbr));
  hero.style.setProperty("--bb-home", railColor(home.abbr));
  hero.appendChild(logoImg(away.abbr, "wm wm-away"));
  hero.appendChild(logoImg(home.abbr, "wm wm-home"));

  const eyebrow = el("div", "hero-eyebrow");
  eyebrow.appendChild(svgIcon("M12 2l2.4 4.9 5.4.8-3.9 3.8.9 5.4L12 14.3 7.2 16.9l.9-5.4L4.2 7.7l5.4-.8z"));
  eyebrow.appendChild(document.createTextNode(`Game of the Week · ${DATA.week.label}`));
  hero.appendChild(eyebrow);

  const face = el("div", "hero-face");
  for (const [t, side] of [[away, "away"], [home, "home"]]) {
    const block = el("div", "hero-team " + side);
    block.appendChild(logoImg(t.abbr, "hero-logo"));
    const name = el("div", "hero-name");
    name.appendChild(el("span", "hero-nick", t.nick.toUpperCase()));
    name.appendChild(el("span", "hero-rec", record(t.teamId) || t.abbr));
    block.appendChild(name);
    face.appendChild(block);
    if (side === "away") face.appendChild(el("div", "hero-vs", "VS"));
  }
  hero.appendChild(face);

  const meta = el("div", "hero-meta");
  const decided = g.played;
  meta.appendChild(el("span", "hero-status", decided ? `FINAL · ${away.abbr} ${g.awayScore} — ${home.abbr} ${g.homeScore}` : "THIS WEEK"));
  if (g.channelUrl) meta.appendChild(el("span", "hero-cta", "Open game channel →"));
  hero.appendChild(meta);
  return hero;
}

function railCard(title, rows) {
  const card = el("div", "card rail-card");
  card.appendChild(el("div", "rail-head", title));
  for (const row of rows) card.appendChild(row);
  return card;
}

function headlineRow(post) {
  const row = el("div", "headline-item");
  const text = post.text.length > 120 ? post.text.slice(0, post.text.lastIndexOf(" ", 120)) + "…" : post.text;
  row.appendChild(el("div", "headline-text", text));
  row.appendChild(el("div", "headline-by", `${post.name} · ${timeAgo(post.postedAt)}`));
  return row;
}

function injuryRow(inj) {
  const row = el("div", "wire-row row-tappable");
  row.addEventListener("click", () => openPlayerCard(inj.id));
  row.appendChild(avatar({ name: inj.name, teamId: inj.teamId, portraitId: inj.portraitId }));
  const who = el("div", "wire-who");
  who.appendChild(el("div", "wire-name", inj.name));
  who.appendChild(el("div", "wire-sub", `${inj.pos} · ${team(inj.teamId).abbr}`));
  row.appendChild(who);
  row.appendChild(el("span", "wire-tag out", inj.weeksOut >= 17 ? "OUT · SEASON" : `OUT ~${inj.weeksOut} WK${inj.weeksOut === 1 ? "" : "S"}`));
  return row;
}

const TX_LABEL = { signed: "SIGN", dropped: "CUT", traded: "TRADE" };

function txRow(tx) {
  const row = el("div", "wire-row");
  row.appendChild(el("span", "wire-tag tx-" + tx.kind, TX_LABEL[tx.kind] || tx.kind.toUpperCase()));
  const who = el("div", "wire-who");
  who.appendChild(el("div", "wire-name", `${tx.playerName}`));
  const from = tx.fromTeamId ? team(tx.fromTeamId).abbr : "FA";
  const to = tx.toTeamId ? team(tx.toTeamId).abbr : "FA";
  who.appendChild(el("div", "wire-sub", `${tx.position} · ${from} → ${to}`));
  row.appendChild(who);
  row.appendChild(el("span", "wire-time", timeAgo(tx.at)));
  return row;
}

/* One finished game as a compact history line: winner bold with the red tick. */
function historyRow(g) {
  const r = el("div", "hist-row");
  if (g.kind === "played") {
    const away = team(g.awayTeamId), home = team(g.homeTeamId);
    const awayWon = g.awayScore > g.homeScore, homeWon = g.homeScore > g.awayScore;
    const side = (t, score, won) => {
      const s = el("div", "hist-side" + (won ? " won" : ""));
      s.appendChild(logoImg(t.abbr, "hist-logo"));
      s.appendChild(el("span", "hist-abbr", t.abbr));
      s.appendChild(el("span", "hist-score", String(score)));
      return s;
    };
    r.appendChild(side(away, g.awayScore, awayWon));
    r.appendChild(el("span", "hist-at", "@"));
    r.appendChild(side(home, g.homeScore, homeWon));
  } else if (g.kind === "forceWin") {
    const w = team(g.winnerTeamId), l = team(g.loserTeamId);
    r.appendChild(logoImg(w.abbr, "hist-logo"));
    r.appendChild(el("span", "hist-text", `${w.abbr} def. ${l.abbr}`));
    r.appendChild(el("span", "chip forced", "Force Win"));
  } else {
    const a = team(g.awayTeamId), h = team(g.homeTeamId);
    r.appendChild(logoImg(a.abbr, "hist-logo"));
    r.appendChild(el("span", "hist-text", `${a.abbr} @ ${h.abbr}`));
    r.appendChild(el("span", "chip fairsim", "Fair Sim"));
  }
  return r;
}

function renderHome(view) {
  const games = (DATA.week.games || []).slice();
  const gotw = games.filter((g) => g.isGotw);
  const rest = games.filter((g) => !g.isGotw);

  if (games.length) view.appendChild(scoreStrip(games));

  const page = el("div", "front");
  const main = el("div", "front-main");
  const rail = el("div", "front-rail");

  if (gotw.length) main.appendChild(heroCard(gotw[0]));

  const pastWeeks = (DATA.history || []).filter((w) => w.label !== DATA.week.label);
  main.appendChild(sectionHead("Scoreboard", scoreWeek ? "" : `${games.length} games`));
  if (pastWeeks.length) {
    const pills = el("div", "week-pills");
    for (const w of pastWeeks) {
      const key = `${w.stage}-${w.week}`;
      const pill = el("button", "week-pill" + (scoreWeek === key ? " active" : ""), w.label.replace("Preseason ", "P"));
      pill.type = "button";
      pill.addEventListener("click", () => { scoreWeek = scoreWeek === key ? null : key; render(); });
      pills.appendChild(pill);
    }
    const now = el("button", "week-pill" + (scoreWeek === null ? " active" : ""), "This Week");
    now.type = "button";
    now.addEventListener("click", () => { scoreWeek = null; render(); });
    pills.appendChild(now);
    main.appendChild(pills);
  }
  if (scoreWeek) {
    const w = pastWeeks.find((x) => `${x.stage}-${x.week}` === scoreWeek);
    const card = el("div", "card");
    for (const g of w ? w.games : []) card.appendChild(historyRow(g));
    if (!w || !w.games.length) card.appendChild(el("div", "empty", "No recorded results for that week."));
    main.appendChild(card);
  } else {
    if (!games.length) main.appendChild(el("div", "empty", "No games on the schedule yet — check back after the next sync."));
    const grid = el("div", "grid games-grid");
    for (const g of [...gotw.slice(1), ...rest]) grid.appendChild(gameCard(g));
    main.appendChild(grid);
  }

  if ((DATA.news || []).length) {
    rail.appendChild(sectionHead("Top Headlines", ""));
    rail.appendChild(railCard("From the insiders", DATA.news.slice(0, 6).map(headlineRow)));
  }
  if ((DATA.injuries || []).length) {
    rail.appendChild(sectionHead("Injury Report", ""));
    rail.appendChild(railCard("Currently out", DATA.injuries.slice(0, 8).map(injuryRow)));
  }
  if ((DATA.transactions || []).length) {
    rail.appendChild(sectionHead("Transactions", ""));
    rail.appendChild(railCard("The wire", DATA.transactions.slice(0, 8).map(txRow)));
  }

  page.appendChild(main);
  if (rail.childNodes.length) { page.appendChild(rail); page.classList.add("has-rail"); }
  view.appendChild(page);
}

function renderStandings(view) {
  const byDivision = new Map();
  for (const row of DATA.standings || []) {
    if (!byDivision.has(row.division)) byDivision.set(row.division, []);
    byDivision.get(row.division).push(row);
  }
  if (!byDivision.size) { view.appendChild(el("div", "empty", "No standings yet.")); return; }
  const grid = el("div", "grid standings-grid");
  for (const [division, rows] of byDivision) {
    const block = el("div", "division-block");
    block.appendChild(el("div", "division-label", division));
    const card = el("div", "card");
    for (const row of rows) {
      const t = team(row.teamId);
      const r = el("button", "standings-row row-link");
      r.type = "button";
      r.addEventListener("click", () => openTeam(row.teamId));
      r.style.setProperty("--rail", railColor(t.abbr));
      r.appendChild(logoImg(t.abbr));
      r.appendChild(el("span", "name", t.nick));
      if (row.streak) {
        const w = row.streak > 0;
        r.appendChild(el("span", "streak " + (w ? "w" : "l"), (w ? "W" : "L") + Math.abs(row.streak)));
      }
      r.appendChild(el("span", "rec", row.ties ? `${row.wins}-${row.losses}-${row.ties}` : `${row.wins}-${row.losses}`));
      r.appendChild(el("span", "pts", `${row.ptsFor} PF · ${row.ptsAgainst} PA`));
      card.appendChild(r);
    }
    block.appendChild(card);
    grid.appendChild(block);
  }
  view.appendChild(grid);
}

function renderRankings(view) {
  view.appendChild(sectionHead("Power Rankings", DATA.weekLabel));
  const card = el("div", "card");
  for (const row of DATA.rankings || []) {
    const t = team(row.teamId);
    const r = el("button", "rank-row row-link");
    r.type = "button";
    r.addEventListener("click", () => openTeam(row.teamId));
    r.style.setProperty("--rail", railColor(t.abbr));
    r.appendChild(el("div", "rank-num", String(row.rank)));
    r.appendChild(logoImg(t.abbr));
    const who = el("div", "rank-team");
    who.appendChild(el("span", "nick", t.nick));
    who.appendChild(el("span", "sub", `${record(row.teamId)}${t.owner ? " · " + t.owner : ""}`));
    r.appendChild(who);
    const d = row.delta;
    const delta = el("span", "delta " + (d > 0 ? "up" : d < 0 ? "down" : "flat"), d > 0 ? `▲ ${d}` : d < 0 ? `▼ ${Math.abs(d)}` : "—");
    r.appendChild(delta);
    card.appendChild(r);
  }
  view.appendChild(card);
}

function renderLeaders(view) {
  const boards = DATA.leaders || [];
  if (!boards.length) { view.appendChild(el("div", "empty", "No stats yet this season.")); return; }
  const grid = el("div", "grid leaders-grid");
  for (const board of boards) {
    const card = el("div", "card leader-card");
    card.appendChild(el("div", "leader-head", board.label));
    const [top, ...others] = board.rows;

    const topRow = el("div", "leader-top row-tappable");
    topRow.addEventListener("click", () => openPlayerCard(top.id));
    topRow.appendChild(avatar(top));
    const who = el("div", "who");
    who.appendChild(el("div", "name", top.name));
    who.appendChild(el("div", "sub", `${top.position} · ${team(top.teamId).nick}`));
    topRow.appendChild(who);
    const val = el("div", "val", top.value.toLocaleString());
    val.appendChild(el("small", null, board.unit));
    topRow.appendChild(val);
    card.appendChild(topRow);

    others.forEach((row, i) => {
      const r = el("div", "leader-row row-tappable");
      r.addEventListener("click", () => openPlayerCard(row.id));
      r.appendChild(el("span", "pos-num", String(i + 2)));
      r.appendChild(avatar(row));
      r.appendChild(el("span", "name", row.name));
      r.appendChild(el("span", "sub", team(row.teamId).abbr));
      r.appendChild(el("span", "val", row.value.toLocaleString()));
      card.appendChild(r);
    });
    grid.appendChild(card);
  }
  view.appendChild(grid);
}

const PERSONA_COLORS = ["#1d9bf0", "#e0245e", "#794bc4", "#17bf63"];

function personaColor(handle) {
  let h = 0;
  for (const ch of handle) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  return PERSONA_COLORS[h % PERSONA_COLORS.length];
}

function newsCard(post) {
  const card = el("div", "card post");
  const head = el("div", "post-head");
  const initialsAv = () => {
    const d = el("div", "post-avatar");
    d.style.background = personaColor(post.handle);
    d.textContent = post.name.split(" ").map((w) => w[0] || "").join("").slice(0, 2).toUpperCase();
    return d;
  };
  let av;
  if (post.avatarUrl) {
    av = el("img", "post-avatar");
    av.src = post.avatarUrl;
    av.alt = post.name;
    av.loading = "lazy";
    av.onerror = () => av.replaceWith(initialsAv());
  } else {
    av = initialsAv();
  }
  head.appendChild(av);
  const who = el("div", "post-who");
  const nameLine = el("div", "post-name", post.name);
  nameLine.appendChild(svgIcon("M12 1.7l2.4 2.3 3.3-.6.6 3.3 3 1.6-1.5 3 1.5 3-3 1.6-.6 3.3-3.3-.6-2.4 2.3-2.4-2.3-3.3.6-.6-3.3-3-1.6 1.5-3-1.5-3 3-1.6.6-3.3 3.3.6zM10.7 14.9l5.2-5.2-1.2-1.2-4 4-1.7-1.7-1.2 1.2z", "verified"));
  who.appendChild(nameLine);
  who.appendChild(el("div", "post-handle", post.handle));
  head.appendChild(who);
  head.appendChild(el("span", "post-time", timeAgo(post.postedAt)));
  card.appendChild(head);
  card.appendChild(el("div", "post-text", post.text));
  return card;
}

function renderNews(view) {
  const posts = DATA.news || [];
  if (!posts.length) { view.appendChild(el("div", "empty", "No league news yet — the insiders post after each advance.")); return; }
  const feed = el("div", "grid feed");
  for (const post of posts) feed.appendChild(newsCard(post));
  view.appendChild(feed);
  view.appendChild(el("div", "news-disclaimer", "League insiders are AI-generated parody personalities built from this league's real synced data. Not real people posting, not real reporting."));
}

/* ---------- Trade builder ----------
   Builds a trade from the rosters already in site.json and encodes it as an
   `FO1.` code — the SAME format src/discord/tradeCode.ts decodes. No server:
   the code is pasted into Discord (/trade import), and Discord supplies the
   identity. Pick values mirror src/discord/draftPickValue.ts's constants. */

const TRADE = {
  a: null, b: null,           // teamIds
  aPlayers: [], bPlayers: [], // rosterIds
  aPicks: [], bPicks: [],     // [round, slotOrNull, yearOffset]
  code: null,                 // generated code, cleared on any edit
};
const tradeSearchQ = { a: "", b: "" }; // transient per-side roster filter, survives re-renders but not reloads

function tradeSaveState() {
  try { localStorage.setItem("trade-draft", JSON.stringify(TRADE)); } catch {}
}
function tradeLoadState() {
  try {
    const saved = JSON.parse(localStorage.getItem("trade-draft") || "null");
    if (saved && typeof saved === "object") Object.assign(TRADE, saved, { code: null });
  } catch {}
}
tradeLoadState();

function base64url(str) {
  return btoa(String.fromCharCode(...new TextEncoder().encode(str)))
    .replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
}

function buildTradeCode() {
  return "FO1." + base64url(JSON.stringify([TRADE.a, TRADE.b, TRADE.aPlayers, TRADE.bPlayers, TRADE.aPicks, TRADE.bPicks]));
}

/* Mirrors computeDraftPickValue in draftPickValue.ts — keep the constants in sync. */
function pickValue(round, slot, yearOffset) {
  const perRound = DATA.picksPerRound || 32;
  const s = Math.min(Math.max(slot == null ? Math.ceil(perRound / 2) : slot, 1), perRound);
  const overall = (round - 1) * perRound + s;
  return Math.round(650 * Math.pow(0.97, overall - 1) * Math.pow(0.85, yearOffset));
}

const YEAR_WORDS = ["this year", "next year", "year after"];
function pickChipLabel(p) {
  const [round, slot, yr] = p;
  return `${round}${["st","nd","rd"][round-1] || "th"} rd${slot ? ` (${round}.${String(slot).padStart(2,"0")})` : ""} · ${YEAR_WORDS[yr]}`;
}

function rosterOf(teamId) { return (DATA.rosters && DATA.rosters[String(teamId)]) || []; }

function sideTotal(teamId, playerIds, picks) {
  const roster = rosterOf(teamId);
  const pv = playerIds.reduce((sum, id) => sum + ((roster.find((p) => p.id === id) || {}).value || 0), 0);
  return pv + picks.reduce((sum, p) => sum + pickValue(p[0], p[1], p[2]), 0);
}

function tradeEdited() { TRADE.code = null; tradeSaveState(); render(); }

function renderTradeSide(container, sideKey) {
  const teamId = TRADE[sideKey];
  const playersKey = sideKey + "Players", picksKey = sideKey + "Picks";
  const t = team(teamId);
  const wrap = el("div", "trade-side");

  const head = el("div", "trade-side-head");
  head.appendChild(logoImg(t.abbr));
  head.appendChild(el("span", "label", `${t.nick} send`));
  head.appendChild(el("span", "side-total", String(sideTotal(teamId, TRADE[playersKey], TRADE[picksKey]))));
  wrap.appendChild(head);

  const chips = el("div", "asset-chips");
  for (const id of TRADE[playersKey]) {
    const p = rosterOf(teamId).find((r) => r.id === id);
    if (!p) continue;
    const chip = el("button", "asset-chip");
    chip.type = "button";
    chip.appendChild(avatar({ name: p.name, teamId, portraitId: p.portraitId }));
    chip.appendChild(el("span", null, p.name));
    chip.appendChild(el("span", "chip-val", String(p.value)));
    chip.appendChild(el("span", "chip-x", "✕"));
    chip.addEventListener("click", () => { TRADE[playersKey] = TRADE[playersKey].filter((x) => x !== id); tradeEdited(); });
    chips.appendChild(chip);
  }
  TRADE[picksKey].forEach((pk, i) => {
    const chip = el("button", "asset-chip");
    chip.type = "button";
    chip.appendChild(el("span", null, "🎟 " + pickChipLabel(pk)));
    chip.appendChild(el("span", "chip-val", String(pickValue(pk[0], pk[1], pk[2]))));
    chip.appendChild(el("span", "chip-x", "✕"));
    chip.addEventListener("click", () => { TRADE[picksKey].splice(i, 1); tradeEdited(); });
    chips.appendChild(chip);
  });
  if (chips.childNodes.length) wrap.appendChild(chips);

  const search = el("input", "roster-search");
  search.type = "search";
  search.placeholder = `Search the ${t.nick} roster…`;
  search.value = tradeSearchQ[sideKey] || "";
  wrap.appendChild(search);

  const listCard = el("div", "card");
  const list = el("div", "roster-list");
  listCard.appendChild(list);
  wrap.appendChild(listCard);

  const renderList = () => {
    const q = search.value.trim().toLowerCase();
    list.replaceChildren();
    const rows = rosterOf(teamId).filter((p) => !q || p.name.toLowerCase().includes(q) || p.pos.toLowerCase() === q);
    for (const p of rows.slice(0, q ? 50 : 200)) {
      const selected = TRADE[playersKey].includes(p.id);
      const item = el("button", "roster-item" + (selected ? " selected" : ""));
      item.type = "button";
      item.appendChild(avatar({ name: p.name, teamId, portraitId: p.portraitId }));
      item.appendChild(el("span", "ri-name", p.name));
      item.appendChild(el("span", "ri-sub", `${p.pos} · ${p.ovr} OVR`));
      item.appendChild(el("span", "ri-val", selected ? "" : String(p.value)));
      if (selected) item.appendChild(el("span", "ri-check", "✓"));
      item.addEventListener("click", () => {
        if (selected) TRADE[playersKey] = TRADE[playersKey].filter((x) => x !== p.id);
        else if (TRADE[playersKey].length < 10) TRADE[playersKey] = [...TRADE[playersKey], p.id];
        tradeEdited();
      });
      list.appendChild(item);
    }
    if (!rows.length) list.appendChild(el("div", "empty", "No players match."));
  };
  search.addEventListener("input", () => { tradeSearchQ[sideKey] = search.value; renderList(); });
  renderList();

  const adder = el("div", "pick-adder");
  const roundSel = el("select");
  for (let r = 1; r <= 7; r++) roundSel.appendChild(new Option(`Round ${r}`, String(r)));
  const yearSel = el("select");
  YEAR_WORDS.forEach((w, i) => yearSel.appendChild(new Option(w[0].toUpperCase() + w.slice(1), String(i))));
  const addBtn = el("button", "add-pick-btn", "+ Pick");
  addBtn.type = "button";
  addBtn.addEventListener("click", () => {
    if (TRADE[picksKey].length >= 10) return;
    TRADE[picksKey] = [...TRADE[picksKey], [Number(roundSel.value), null, Number(yearSel.value)]];
    tradeEdited();
  });
  adder.appendChild(roundSel);
  adder.appendChild(yearSel);
  adder.appendChild(addBtn);
  wrap.appendChild(adder);

  container.appendChild(wrap);
}

function renderTrade(view) {
  if (!DATA.rosters) {
    view.appendChild(el("div", "empty", "Trade data isn't in this site version yet — it appears after the next league sync."));
    return;
  }
  view.appendChild(sectionHead("Trade Builder", "no login needed"));
  view.appendChild(el("p", "trade-intro", "Build the deal here, then paste the code into Discord — the bot opens it for review and the committee vote. Whoever pastes it is the proposer."));

  const pickers = el("div", "trade-teams");
  for (const key of ["a", "b"]) {
    const sel = el("select", "team-select");
    sel.appendChild(new Option(key === "a" ? "Team A…" : "Team B…", ""));
    for (const t of [...DATA.teams].sort((x, y) => x.nick.localeCompare(y.nick))) {
      const opt = new Option(t.nick, String(t.teamId));
      opt.selected = TRADE[key] === t.teamId;
      sel.appendChild(opt);
    }
    sel.addEventListener("change", () => {
      TRADE[key] = sel.value ? Number(sel.value) : null;
      TRADE[key + "Players"] = [];
      TRADE[key + "Picks"] = [];
      tradeEdited();
    });
    pickers.appendChild(sel);
    if (key === "a") pickers.appendChild(el("div", "swap-glyph", "⇄"));
  }
  view.appendChild(pickers);

  if (!TRADE.a || !TRADE.b) {
    view.appendChild(el("div", "empty", "Pick both teams to start building."));
    return;
  }
  if (TRADE.a === TRADE.b) {
    view.appendChild(el("div", "empty", "Pick two different teams."));
    return;
  }

  const sides = el("div", "grid trade-sides");
  renderTradeSide(sides, "a");
  renderTradeSide(sides, "b");
  view.appendChild(sides);

  const totalA = sideTotal(TRADE.a, TRADE.aPlayers, TRADE.aPicks);
  const totalB = sideTotal(TRADE.b, TRADE.bPlayers, TRADE.bPicks);
  const hasAssets = TRADE.aPlayers.length + TRADE.bPlayers.length + TRADE.aPicks.length + TRADE.bPicks.length > 0;

  const summary = el("div", "trade-summary");
  const totals = el("div", "totals");
  totals.appendChild(el("span", null, `${team(TRADE.a).abbr} ${totalA}`));
  totals.appendChild(el("span", null, `${team(TRADE.b).abbr} ${totalB}`));
  summary.appendChild(totals);
  // Same math as trade.ts's fairnessLine: whoever SENDS more value favors the other side.
  const combined = totalA + totalB;
  const pct = combined > 0 ? (Math.abs(totalA - totalB) / (combined / 2)) * 100 : 0;
  const verdict = !hasAssets ? "Add players or picks to either side." : pct < 10 ? `Roughly even (within ${pct.toFixed(0)}%).` : `Favors ${totalA > totalB ? team(TRADE.b).nick : team(TRADE.a).nick} by ~${pct.toFixed(0)}%.`;
  summary.appendChild(el("div", "fairness", verdict));

  // Direct submission (when the league has the Worker set up) is the primary CTA;
  // the copy-a-code flow stays as the always-available fallback underneath.
  const directAvailable = Boolean(DATA.submitUrl);
  let siteKey = null;
  try { siteKey = localStorage.getItem("site-key"); } catch {}

  if (directAvailable && !siteKey) {
    const keyRow = el("div");
    const keyInput = el("input", "roster-search");
    keyInput.type = "password";
    keyInput.placeholder = "Paste your key from /site-key (one time)";
    keyInput.autocomplete = "off";
    const keyHint = el("div", "trade-code-hint");
    keyHint.append("To submit straight to Discord, run ");
    keyHint.appendChild(el("code", null, "/site-key"));
    keyHint.append(" there once — tapping the link it DMs you sets this up automatically (or paste the key here).");
    keyInput.addEventListener("change", () => {
      const v = keyInput.value.trim();
      if (v.startsWith("FOK1.")) {
        try { localStorage.setItem("site-key", v); } catch {}
        render();
      }
    });
    keyRow.appendChild(keyInput);
    keyRow.appendChild(keyHint);
    summary.appendChild(keyRow);
  }

  if (directAvailable && siteKey) {
    const submitBtn = el("button", "trade-cta", "Submit to League");
    submitBtn.type = "button";
    submitBtn.disabled = !hasAssets;
    const status = el("div", "trade-code-hint");
    submitBtn.addEventListener("click", async () => {
      submitBtn.disabled = true;
      submitBtn.textContent = "Submitting…";
      status.textContent = "";
      try {
        const res = await fetch(DATA.submitUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ key: siteKey, code: buildTradeCode() }),
        });
        const out = await res.json().catch(() => ({}));
        if (res.ok && out.ok) {
          submitBtn.textContent = "Submitted ✓";
          submitBtn.classList.add("copied-flash");
          status.textContent = "Sent to the league — the trade card is posting to Discord now. If something's off with it, the bot will DM you why.";
        } else {
          submitBtn.disabled = false;
          submitBtn.textContent = "Submit to League";
          if (res.status === 403) {
            try { localStorage.removeItem("site-key"); } catch {}
            status.textContent = "Your key was rejected — run /site-key in Discord for a fresh one, then paste it here again.";
            setTimeout(render, 2500);
          } else {
            status.textContent = (out.error || "Couldn't submit right now.") + " You can still use the trade code below.";
          }
        }
      } catch {
        submitBtn.disabled = false;
        submitBtn.textContent = "Submit to League";
        status.textContent = "Couldn't reach the league server — check your connection, or use the trade code below.";
      }
    });
    summary.appendChild(submitBtn);
    summary.appendChild(status);
  }

  const cta = el("button", "trade-cta" + (directAvailable && siteKey ? " trade-cta-secondary" : ""), TRADE.code ? "Copy Again" : "Get Trade Code");
  cta.type = "button";
  cta.disabled = !hasAssets;
  cta.addEventListener("click", async () => {
    TRADE.code = buildTradeCode();
    try { await navigator.clipboard.writeText(TRADE.code); cta.textContent = "Copied!"; cta.classList.add("copied-flash"); } catch {}
    tradeSaveState();
    render();
  });
  summary.appendChild(cta);

  if (TRADE.code) {
    summary.appendChild(el("div", "trade-code-box", TRADE.code));
    const hint = el("div", "trade-code-hint");
    hint.append("Copied. In Discord, run ");
    const cmd = el("code", null, "/trade import");
    hint.appendChild(cmd);
    hint.append(" and paste this as the code. The bot opens the trade for review — Evaluate, then Submit to the committee.");
    summary.appendChild(hint);
  }
  view.appendChild(summary);
}

/* ---------- Team page ---------- */

const DEV_ORDER = { "X-Factor": 3, "Superstar": 2, "Star": 1, "Normal": 0 };

function renderTeam(view, teamId) {
  const t = team(teamId);
  const standing = (DATA.standings || []).find((s) => s.teamId === teamId);
  const rankRow = (DATA.rankings || []).find((r) => r.teamId === teamId);
  const roster = (DATA.rosters && DATA.rosters[String(teamId)]) || [];

  const back = el("button", "team-back", "← Back");
  back.type = "button";
  back.addEventListener("click", () => closeTeam(false));
  view.appendChild(back);

  // Hero banner in the team's colors with the oversized watermark
  const hero = el("div", "team-hero");
  hero.style.setProperty("--bb-away", railColor(t.abbr));
  hero.style.setProperty("--bb-home", teamColor(t.abbr));
  hero.appendChild(logoImg(t.abbr, "wm wm-away"));
  const head = el("div", "team-hero-head");
  head.appendChild(logoImg(t.abbr, "team-hero-logo"));
  const who = el("div");
  who.appendChild(el("div", "team-hero-city", (t.city || "").toUpperCase()));
  who.appendChild(el("div", "team-hero-nick", t.nick.toUpperCase()));
  const bits = [record(teamId), t.division, t.owner ? "Owner: " + t.owner : null].filter(Boolean).join(" · ");
  who.appendChild(el("div", "team-hero-sub", bits));
  head.appendChild(who);
  hero.appendChild(head);
  view.appendChild(hero);

  // Stat chips
  const chips = el("div", "team-chips");
  const chip = (label, value) => {
    const d = el("div", "team-chip");
    d.appendChild(el("div", "team-chip-val", String(value)));
    d.appendChild(el("div", "team-chip-label", label));
    return d;
  };
  chips.appendChild(chip("Team OVR", t.ovr));
  if (t.grade) chips.appendChild(chip("Roster Grade", `${t.grade.letter} · ${t.grade.percentile}th pct`));
  if (rankRow) chips.appendChild(chip("Power Rank", "#" + rankRow.rank));
  if (standing) {
    chips.appendChild(chip("PF (per gm)", standing.ptsFor));
    chips.appendChild(chip("PA (per gm)", standing.ptsAgainst));
    if (standing.offYdsRank) chips.appendChild(chip("Off Yds Rank", "#" + standing.offYdsRank));
    if (standing.defYdsRank) chips.appendChild(chip("Def Yds Rank", "#" + standing.defYdsRank));
  }
  if (t.gotwCount) chips.appendChild(chip("GOTW Features", t.gotwCount + "x"));
  view.appendChild(chips);

  // Team Identity — the season's real box-score tendencies. Built for the GM
  // deciding what to build, change, or adapt: play-calling split, efficiency,
  // ball distribution, and where the defense actually bends.
  const tend = (DATA.tendencies || {})[String(teamId)];
  if (tend) {
    view.appendChild(sectionHead("Team Identity", `${tend.weeks ?? tend.games} weeks of box scores`));
    const idCard = el("div", "card id-card");

    const split = el("div", "id-split");
    const runW = Math.max(6, Math.min(94, tend.runPct));
    const bar = el("div", "id-split-bar");
    const run = el("div", "id-split-run");
    run.style.width = runW + "%";
    bar.appendChild(run);
    split.appendChild(el("div", "id-split-label", `RUN ${tend.runPct}%`));
    split.appendChild(bar);
    split.appendChild(el("div", "id-split-label", `PASS ${100 - tend.runPct}%`));
    idCard.appendChild(split);
    idCard.appendChild(el("div", "id-split-sub", `${tend.rushAtt} carries · ${tend.passAtt} dropbacks`));

    const cell = (val, label) => {
      const d = el("div", "id-cell");
      d.appendChild(el("div", "id-cell-val", String(val)));
      d.appendChild(el("div", "id-cell-label", label));
      return d;
    };
    const grid = el("div", "id-grid");
    grid.appendChild(cell(`${tend.passYdsPg} #${tend.passYdsPgRank}`, "Pass yds/gm"));
    grid.appendChild(cell(`${tend.rushYdsPg} #${tend.rushYdsPgRank}`, "Rush yds/gm"));
    grid.appendChild(cell(`${tend.passTDs}–${tend.rushTDs}`, "Pass–Rush TDs"));
    grid.appendChild(cell(tend.thirdDownPct + "%", "3rd down"));
    grid.appendChild(cell(tend.redZoneTdPct + "%", "Red zone TD"));
    grid.appendChild(cell(tend.sacksAllowed, "Sacks allowed"));
    grid.appendChild(cell(tend.giveaways, "Giveaways"));
    grid.appendChild(cell(tend.takeaways, "Takeaways"));
    grid.appendChild(cell(`${tend.defPassYdsPg} #${tend.defPassYdsPgRank}`, "Pass yds/gm allowed"));
    grid.appendChild(cell(`${tend.defRushYdsPg} #${tend.defRushYdsPgRank}`, "Rush yds/gm allowed"));
    grid.appendChild(cell(tend.defSacks, "Def sacks"));
    idCard.appendChild(grid);

    const shareRow = (r, sub) => {
      const d = el("div", "share-row row-tappable");
      d.addEventListener("click", () => openPlayerCard(r.id));
      d.appendChild(avatar({ name: r.name, teamId, portraitId: r.portraitId }));
      const who = el("div", "share-who");
      const top = el("div", "share-top");
      top.appendChild(el("span", "wire-name", r.name));
      top.appendChild(el("span", "share-pct", r.sharePct + "%"));
      who.appendChild(top);
      const barWrap = el("div", "share-bar");
      const fill = el("div", "share-bar-fill");
      fill.style.width = Math.min(100, r.sharePct) + "%";
      barWrap.appendChild(fill);
      who.appendChild(barWrap);
      who.appendChild(el("div", "wire-sub", sub));
      d.appendChild(who);
      return d;
    };
    if ((tend.targets || []).length) {
      idCard.appendChild(el("div", "need-depth-label", "Target share"));
      for (const r of tend.targets) idCard.appendChild(shareRow(r, `${r.pos} · ${r.catches} catches · ${r.yds} yds · ${r.tds} TD`));
    }
    if ((tend.rushers || []).length) {
      idCard.appendChild(el("div", "need-depth-label", "Carry share"));
      for (const r of tend.rushers) idCard.appendChild(shareRow(r, `${r.pos} · ${r.att} att · ${r.yds} yds · ${r.tds} TD`));
    }
    idCard.appendChild(el("div", "news-disclaimer id-note", "Target share ≈ catches + drops (EA's export doesn't log true targets, formations, or personnel packages — nothing here is invented)."));
    view.appendChild(idCard);
  }

  // CSV export — real static files written at publish time; `download` names the save
  const exports = el("div", "team-exports");
  const csvBtn = el("a", "trade-cta csv-btn", "⬇ Export Roster CSV");
  csvBtn.href = "csv/team-" + teamId + ".csv";
  csvBtn.setAttribute("download", (t.nick || "team") + "-roster.csv");
  exports.appendChild(csvBtn);
  const allBtn = el("a", "csv-all-link", "or download every player in the league (CSV)");
  allBtn.href = "csv/all-players.csv";
  allBtn.setAttribute("download", "all-players.csv");
  exports.appendChild(allBtn);
  view.appendChild(exports);

  // Season results — this team's game log from the recorded history
  const log = [];
  for (const w of DATA.history || []) {
    for (const g of w.games) {
      if (g.kind === "played" && (g.awayTeamId === teamId || g.homeTeamId === teamId)) {
        const home = g.homeTeamId === teamId;
        const oppId = home ? g.awayTeamId : g.homeTeamId;
        const my = home ? g.homeScore : g.awayScore, their = home ? g.awayScore : g.homeScore;
        log.push({ label: w.label, opp: team(oppId), home, result: my > their ? "W" : my < their ? "L" : "T", score: `${my}-${their}` });
      } else if (g.kind === "forceWin" && (g.winnerTeamId === teamId || g.loserTeamId === teamId)) {
        log.push({ label: w.label, opp: team(g.winnerTeamId === teamId ? g.loserTeamId : g.winnerTeamId), home: null, result: g.winnerTeamId === teamId ? "W" : "L", score: "Force Win" });
      } else if (g.kind === "fairSim" && (g.awayTeamId === teamId || g.homeTeamId === teamId)) {
        log.push({ label: w.label, opp: team(g.awayTeamId === teamId ? g.homeTeamId : g.awayTeamId), home: g.homeTeamId === teamId, result: "—", score: "Fair Sim" });
      }
    }
  }
  if (log.length) {
    view.appendChild(sectionHead("Season Results", log.length + " games"));
    const logCard = el("div", "card");
    for (const row of log) {
      const r = el("div", "gamelog-row");
      r.appendChild(el("span", "gamelog-week", row.label.replace("Preseason ", "P").replace("Week ", "W")));
      r.appendChild(el("span", "wl-badge wl-" + row.result.toLowerCase().replace("—", "t"), row.result));
      r.appendChild(logoImg(row.opp.abbr, "hist-logo"));
      r.appendChild(el("span", "gamelog-opp", (row.home === null ? "" : row.home ? "vs " : "@ ") + row.opp.nick));
      r.appendChild(el("span", "gamelog-score", row.score));
      logCard.appendChild(r);
    }
    view.appendChild(logCard);
  }

  // Draft Board — every position group, tappable: score meter, the engine's full
  // reasoning, and that group's actual depth chart.
  const needs = (DATA.needs && DATA.needs[String(teamId)]) || [];
  if (needs.length) {
    view.appendChild(sectionHead("Draft Board", "tap a position for the full picture"));

    const sorts = el("div", "week-pills");
    for (const [key, label] of [["need", "By need"], ["pos", "By position"]]) {
      const pill = el("button", "week-pill" + (needsView.sort === key ? " active" : ""), label);
      pill.type = "button";
      pill.addEventListener("click", () => { needsView.sort = key; render(); });
      sorts.appendChild(pill);
    }
    view.appendChild(sorts);

    const POS_ORDER = ["QB", "RB", "WR", "TE", "OL", "EDGE", "DT", "LB", "CB", "S", "Specialists"];
    const list = needsView.sort === "pos" ? [...needs].sort((a, b) => POS_ORDER.indexOf(a.label) - POS_ORDER.indexOf(b.label)) : needs;

    const needCard = el("div", "card");
    const maxScore = 40;
    for (const n of list) {
      const isOpen = needsView.open === n.label;
      const r = el("button", "need-row" + (isOpen ? " open" : ""));
      r.type = "button";
      r.addEventListener("click", () => { needsView.open = isOpen ? null : n.label; render(); });

      const head = el("div", "need-head");
      head.appendChild(el("span", "need-pos", n.label));
      head.appendChild(el("span", "need-level lv-" + n.level.toLowerCase(), n.level));
      head.appendChild(el("span", "need-starter", n.starter ? `${n.starter.name} · ${n.starter.ovr} OVR` : "nobody rostered"));
      head.appendChild(el("span", "need-caret", isOpen ? "▴" : "▾"));
      r.appendChild(head);

      const meter = el("div", "need-meter");
      const fill = el("div", "need-meter-fill lv-" + n.level.toLowerCase());
      fill.style.width = Math.min(100, Math.round(((n.score || 0) / maxScore) * 100)) + "%";
      meter.appendChild(fill);
      r.appendChild(meter);

      if (isOpen) {
        const detail = el("div", "need-detail");
        for (const reason of n.reasons || []) detail.appendChild(el("div", "need-reason", "• " + reason));
        if ((n.depth || []).length) {
          detail.appendChild(el("div", "need-depth-label", "Depth chart"));
          n.depth.forEach((p, i) => {
            const d = el("div", "need-depth-row row-tappable");
            // Inside the need-row <button> — stop the bubble or the tap also
            // collapses the group the player sits in.
            d.addEventListener("click", (e) => { e.stopPropagation(); openPlayerCard(p.id); });
            d.appendChild(el("span", "pos-num", String(i + 1)));
            d.appendChild(avatar({ name: p.name, teamId, portraitId: p.portraitId }));
            d.appendChild(el("span", "wire-name", p.name));
            d.appendChild(el("span", "wire-sub", `${p.pos} · ${p.age} yrs`));
            const devWrap = el("span", "player-dev");
            devWrap.appendChild(el("span", "dev-badge dev-" + (p.dev || "Normal").toLowerCase().replace(/[^a-z]/g, ""), p.dev || "—"));
            d.appendChild(devWrap);
            d.appendChild(el("span", "player-ovr", String(p.ovr)));
            detail.appendChild(d);
          });
        } else {
          detail.appendChild(el("div", "need-reason", "Nobody rostered at this group."));
        }
        const fits = bestFreeAgentsFor(n.label, 3);
        if (fits.length && n.level !== "SOLID") {
          detail.appendChild(el("div", "need-depth-label", "Best available free agents"));
          for (const p of fits) detail.appendChild(faRow(p));
        }
        r.appendChild(detail);
      }
      needCard.appendChild(r);
    }
    view.appendChild(needCard);
  }

  // Sortable roster table
  view.appendChild(sectionHead("Roster", roster.length + " players"));
  if (!roster.length) { view.appendChild(el("div", "empty", "No roster data — appears after the next sync.")); return; }

  const wrap = el("div", "card table-wrap");
  const table = el("table", "roster-table");
  const thead = el("thead");
  const headRow = el("tr");
  const cols = [
    { key: "name", label: "Player", sort: (p) => p.name },
    { key: "pos", label: "POS", sort: (p) => p.pos },
    { key: "ovr", label: "OVR", sort: (p) => p.ovr },
    { key: "dev", label: "DEV", sort: (p) => DEV_ORDER[p.dev] ?? -1 },
    { key: "age", label: "AGE", sort: (p) => p.age },
    { key: "value", label: "VALUE", sort: (p) => p.value },
  ];
  for (const col of cols) {
    const th = el("th", teamSort.col === col.key ? "sorted" : "");
    th.textContent = col.label + (teamSort.col === col.key ? (teamSort.dir === -1 ? " ▾" : " ▴") : "");
    th.addEventListener("click", () => {
      if (teamSort.col === col.key) teamSort.dir *= -1;
      else { teamSort.col = col.key; teamSort.dir = col.key === "name" || col.key === "pos" ? 1 : -1; }
      render();
    });
    headRow.appendChild(th);
  }
  thead.appendChild(headRow);
  table.appendChild(thead);

  const colDef = cols.find((col) => col.key === teamSort.col) || cols[2];
  const sorted = roster.slice().sort((a, b) => {
    const va = colDef.sort(a), vb = colDef.sort(b);
    return (va < vb ? -1 : va > vb ? 1 : 0) * teamSort.dir;
  });

  const tbody = el("tbody");
  for (const p of sorted) {
    const tr = el("tr", "row-tappable");
    tr.addEventListener("click", () => openPlayerCard(p.id));
    const nameTd = el("td", "rt-name");
    nameTd.appendChild(avatar({ name: p.name, teamId, portraitId: p.portraitId }));
    nameTd.appendChild(el("span", null, p.name));
    tr.appendChild(nameTd);
    tr.appendChild(el("td", null, p.pos));
    tr.appendChild(el("td", "rt-num", String(p.ovr)));
    const devTd = el("td");
    devTd.appendChild(el("span", "dev-badge dev-" + (p.dev || "Normal").toLowerCase().replace(/[^a-z]/g, ""), p.dev || "—"));
    tr.appendChild(devTd);
    tr.appendChild(el("td", "rt-num", String(p.age ?? "—")));
    tr.appendChild(el("td", "rt-num", p.value.toLocaleString()));
    tbody.appendChild(tr);
  }
  table.appendChild(tbody);
  wrap.appendChild(table);
  view.appendChild(wrap);
  view.appendChild(el("div", "news-disclaimer", "Full attributes, contracts, and every rating are in the CSV export above."));
}

/* ---------- Draft HQ ---------- */

const DRAFT_GROUP_POS = {
  QB: ["QB"], RB: ["HB", "FB"], WR: ["WR"], TE: ["TE"],
  OL: ["LT", "LG", "C", "RG", "RT"], EDGE: ["LEDG", "REDG"], DT: ["DT"],
  LB: ["SAM", "WILL", "MIKE"], CB: ["CB"], S: ["FS", "SS"], Specialists: ["K", "P", "LS"],
};
const DRAFT_GROUPS = Object.keys(DRAFT_GROUP_POS);
const hqState = { faGroup: "", pickRound: 1, pickSlot: "", pickYear: 0 };

function bestFreeAgentsFor(group, limit) {
  const positions = DRAFT_GROUP_POS[group];
  return (DATA.freeAgents || []).filter((p) => !positions || positions.includes(p.pos)).slice(0, limit);
}

function faRow(p) {
  const r = el("div", "wire-row row-tappable");
  // Also used nested inside need-row <button>s — stop the bubble.
  r.addEventListener("click", (e) => { e.stopPropagation(); openPlayerCard(p.id); });
  r.appendChild(avatar({ name: p.name, teamId: -1, portraitId: p.portraitId }));
  const who = el("div", "wire-who");
  who.appendChild(el("div", "wire-name", p.name));
  who.appendChild(el("div", "wire-sub", `${p.pos} · ${p.age} yrs · value ${p.value.toLocaleString()}`));
  r.appendChild(who);
  const devWrap = el("span", "player-dev");
  devWrap.appendChild(el("span", "dev-badge dev-" + (p.dev || "Normal").toLowerCase().replace(/[^a-z]/g, ""), p.dev || "—"));
  r.appendChild(devWrap);
  r.appendChild(el("span", "player-ovr", String(p.ovr)));
  return r;
}

function renderDraftHq(view) {
  const back = el("button", "team-back", "← Back");
  back.type = "button";
  back.addEventListener("click", () => { viewDraftHq = false; try { history.pushState(null, "", location.pathname + location.search); } catch {} render(); });
  view.appendChild(back);

  view.appendChild(sectionHead("Draft HQ", "the whole league's draft picture"));

  // --- League needs matrix ---
  view.appendChild(sectionHead("League Needs", "tap a team for its full board"));
  const wrap = el("div", "card table-wrap");
  const table = el("table", "needs-matrix");
  const thead = el("thead");
  const hr = el("tr");
  hr.appendChild(el("th", null, "Team"));
  for (const g of DRAFT_GROUPS) hr.appendChild(el("th", null, g === "Specialists" ? "SPEC" : g));
  thead.appendChild(hr);
  table.appendChild(thead);
  const tbody = el("tbody");
  const byNeed = [...(DATA.teams || [])].sort((a, b) => a.nick.localeCompare(b.nick));
  for (const t of byNeed) {
    const tr = el("tr");
    tr.addEventListener("click", () => openTeam(t.teamId));
    const teamTd = el("td", "nm-team");
    teamTd.appendChild(logoImg(t.abbr, "hist-logo"));
    teamTd.appendChild(el("span", null, t.abbr));
    tr.appendChild(teamTd);
    const needs = (DATA.needs && DATA.needs[String(t.teamId)]) || [];
    for (const g of DRAFT_GROUPS) {
      const n = needs.find((x) => x.label === g);
      const td = el("td", "nm-cell");
      td.appendChild(el("span", "nm-dot lv-" + (n ? n.level.toLowerCase() : "solid")));
      tr.appendChild(td);
    }
    tbody.appendChild(tr);
  }
  table.appendChild(tbody);
  wrap.appendChild(table);
  view.appendChild(wrap);
  const legend = el("div", "nm-legend");
  for (const [lv, label] of [["high", "High need"], ["medium", "Medium"], ["low", "Low"], ["solid", "Solid"]]) {
    const item = el("span", "nm-legend-item");
    item.appendChild(el("span", "nm-dot lv-" + lv));
    item.appendChild(document.createTextNode(" " + label));
    legend.appendChild(item);
  }
  view.appendChild(legend);

  // --- Best available free agents ---
  view.appendChild(sectionHead("Best Available", "free agents, right now"));
  const pills = el("div", "week-pills");
  for (const g of ["", ...DRAFT_GROUPS]) {
    const pill = el("button", "week-pill" + (hqState.faGroup === g ? " active" : ""), g === "" ? "All" : g === "Specialists" ? "SPEC" : g);
    pill.type = "button";
    pill.addEventListener("click", () => { hqState.faGroup = g; render(); });
    pills.appendChild(pill);
  }
  view.appendChild(pills);
  const faCard = el("div", "card");
  const fas = hqState.faGroup ? bestFreeAgentsFor(hqState.faGroup, 12) : (DATA.freeAgents || []).slice(0, 12);
  for (const p of fas) faCard.appendChild(faRow(p));
  if (!fas.length) faCard.appendChild(el("div", "empty", "No free agents in this group right now."));
  view.appendChild(faCard);

  // --- Pick value calculator ---
  view.appendChild(sectionHead("Pick Value", "the same chart /trade uses"));
  const calc = el("div", "card pick-calc");
  const row = el("div", "pick-adder");
  const roundSel = el("select");
  for (let r = 1; r <= 7; r++) { const o = new Option(`Round ${r}`, String(r)); o.selected = hqState.pickRound === r; roundSel.appendChild(o); }
  const slotSel = el("select");
  slotSel.appendChild(new Option("Slot: TBD", ""));
  for (let s = 1; s <= (DATA.picksPerRound || 32); s++) { const o = new Option(`Pick ${s}`, String(s)); o.selected = hqState.pickSlot === String(s); slotSel.appendChild(o); }
  const yearSel = el("select");
  YEAR_WORDS.forEach((w, i) => { const o = new Option(w[0].toUpperCase() + w.slice(1), String(i)); o.selected = hqState.pickYear === i; yearSel.appendChild(o); });
  for (const [sel, key] of [[roundSel, "pickRound"], [slotSel, "pickSlot"], [yearSel, "pickYear"]]) {
    sel.addEventListener("change", () => { hqState[key] = key === "pickSlot" ? sel.value : Number(sel.value); render(); });
  }
  row.appendChild(roundSel); row.appendChild(slotSel); row.appendChild(yearSel);
  calc.appendChild(row);
  const val = pickValue(hqState.pickRound, hqState.pickSlot === "" ? null : Number(hqState.pickSlot), hqState.pickYear);
  const out = el("div", "pick-calc-out");
  out.appendChild(el("span", "pick-calc-val", val.toLocaleString()));
  out.appendChild(el("span", "pick-calc-label", "trade value — same scale as player values in the Trade tab"));
  calc.appendChild(out);
  view.appendChild(calc);
}

/* ---------- Free Agents (fit engine) ---------- */

const POS_TO_GROUP = {};
for (const [g, positions] of Object.entries(DRAFT_GROUP_POS)) for (const p of positions) POS_TO_GROUP[p] = g;
// Legacy Madden position codes (pre-M27 snapshots) map onto the same groups.
Object.assign(POS_TO_GROUP, { LOLB: "EDGE", ROLB: "EDGE", MLB: "LB", LE: "EDGE", RE: "EDGE", LEDGE: "EDGE", REDGE: "EDGE" });

const faView = { teamId: null, pos: "", q: "", sort: { col: "ovr", dir: -1 }, showAll: false, showAllCols: false };
try { faView.teamId = Number(localStorage.getItem("fa-team")) || null; } catch {}

/* Madden-standard rating abbreviations. Full names feed th tooltips. */
const RATING_NAMES = {
  spd: "Speed", acc: "Acceleration", agi: "Agility", cod: "Change of Direction",
  str: "Strength", awr: "Awareness", thp: "Throw Power", sac: "Short Accuracy",
  mac: "Medium Accuracy", dac: "Deep Accuracy", cth: "Catching", spc: "Spectacular Catch",
  rls: "Release", srr: "Short Route", mrr: "Medium Route", drr: "Deep Route",
  car: "Carrying", btk: "Break Tackle", jkm: "Juke Move", trk: "Trucking",
  rbk: "Run Block", rbp: "Run Block Power", pbk: "Pass Block", pbp: "Pass Block Power",
  ibl: "Impact Block", pmv: "Power Moves", fmv: "Finesse Moves", bsh: "Block Shedding",
  pur: "Pursuit", tak: "Tackle", pow: "Hit Power", prc: "Play Recognition",
  mcv: "Man Coverage", zcv: "Zone Coverage", prs: "Press", kpw: "Kick Power", kac: "Kick Accuracy",
};
/* The DEFAULT columns per position group — advisement about what matters, never a
   cage: every rating ships for every player, and the "+ All ratings" toggle opens
   the full set in any view. */
const GROUP_RATING_COLS = {
  "": ["spd", "acc", "agi", "str", "awr"],
  QB: ["thp", "sac", "mac", "dac", "awr", "spd", "acc", "agi"],
  RB: ["spd", "acc", "agi", "cod", "car", "btk", "jkm", "trk", "cth"],
  WR: ["spd", "acc", "cth", "spc", "rls", "srr", "mrr", "drr", "agi", "cod"],
  TE: ["cth", "spc", "srr", "mrr", "rbk", "pbk", "spd", "str", "awr"],
  OL: ["pbk", "pbp", "rbk", "rbp", "ibl", "str", "awr", "agi"],
  EDGE: ["pmv", "fmv", "bsh", "spd", "acc", "str", "pur", "tak", "pow"],
  DT: ["bsh", "pmv", "fmv", "str", "tak", "pur", "acc", "awr"],
  LB: ["tak", "pur", "prc", "zcv", "mcv", "bsh", "pow", "spd", "acc"],
  CB: ["mcv", "zcv", "prs", "spd", "acc", "agi", "cod", "prc", "cth"],
  S: ["zcv", "mcv", "tak", "pur", "prc", "spd", "pow", "cth"],
  Specialists: ["kpw", "kac", "awr"],
};

/**
 * How much this free agent helps THIS team, from real data only: the needs
 * engine's level at his position group, whether he beats the current starter,
 * dev-trait/age upside, and raw quality. (EA's export has no personality or
 * scheme fields — everything here is grounded in what actually syncs.)
 */
function fitFor(fa, teamId) {
  const group = POS_TO_GROUP[fa.pos] || fa.pos;
  const needs = (DATA.needs && DATA.needs[String(teamId)]) || [];
  const need = needs.find((n) => n.label === group);
  const starter = need && need.depth && need.depth[0];
  let score = 0;
  const reasons = [];

  if (!need) {
    // Unknown position group (unmapped code) — judge on quality alone, honestly.
    reasons.push(`No needs data for ${group} — judged on quality alone`);
  } else if (need.level === "HIGH") { score += 40; reasons.push(`${group} is a HIGH need for your roster`); }
  else if (need.level === "MEDIUM") { score += 25; reasons.push(`${group} is a medium need for you`); }
  else if (need.level === "LOW") { score += 10; reasons.push(`${group} is a low need — nice-to-have`); }
  else reasons.push(`${group} is already solid for you`);

  if (!need) { /* no roster comparison possible */ }
  else if (!starter) { score += 25; reasons.push("You have nobody rostered at this spot — instant starter"); }
  else {
    const diff = fa.ovr - starter.ovr;
    if (diff >= 2) { score += 25; reasons.push(`Would start immediately — beats ${starter.name} (${starter.ovr} OVR) by ${diff}`); }
    else if (diff >= -3) { score += 12; reasons.push(`Pushes ${starter.name} (${starter.ovr} OVR) for the job`); }
    else reasons.push(`Depth behind ${starter.name} (${starter.ovr} OVR)`);
  }

  if (fa.age <= 25 && fa.dev !== "Normal") { score += 15; reasons.push(`${fa.dev} dev at ${fa.age} — real upside to grow`); }
  else if (fa.age >= 31) { score -= 8; reasons.push(`${fa.age} years old — a short-term rental`); }
  if (fa.ovr >= 85) { score += 10; reasons.push("Plug-and-play starter quality"); }

  const verdict = score >= 65 ? "GREAT FIT" : score >= 42 ? "GOOD FIT" : score >= 22 ? "DEPTH" : "LUXURY";
  return { score, verdict, reasons };
}

function renderFreeAgents(view) {
  const pool = DATA.freeAgents || [];
  view.appendChild(sectionHead("Free Agents", `all ${pool.length} players · every column sorts`));

  // Controls: search + optional advise-as team + position pills. The team pick
  // only ADDS a Fit column — it never gates or trims the list.
  const controls = el("div", "fa-controls");
  const search = el("input", "roster-search");
  search.type = "search";
  search.placeholder = "Search by name…";
  search.value = faView.q;
  // Partial re-render on input, same as the Players tab: a full render() would
  // replace the input mid-keystroke, dropping focus (and the iOS keyboard).
  // Re-chunking (showAll = false) keeps per-keystroke rebuilds bounded — the
  // Show All button reappears, so nothing is ever locked away.
  search.addEventListener("input", () => { faView.q = search.value; faView.showAll = false; renderGrid(); });
  controls.appendChild(search);
  const sel = el("select", "team-select");
  sel.appendChild(new Option("Advise for a team… (optional)", ""));
  for (const t of [...DATA.teams].sort((a, b) => a.nick.localeCompare(b.nick))) {
    const opt = new Option(`${t.city} ${t.nick}`, String(t.teamId));
    opt.selected = faView.teamId === t.teamId;
    sel.appendChild(opt);
  }
  sel.addEventListener("change", () => {
    faView.teamId = sel.value ? Number(sel.value) : null;
    faView.showAll = false;
    if (faView.sort.col === "fit" && !faView.teamId) faView.sort = { col: "ovr", dir: -1 };
    try { localStorage.setItem("fa-team", sel.value); } catch {}
    renderGrid();
  });
  controls.appendChild(sel);
  view.appendChild(controls);

  const posPills = el("div", "week-pills");
  for (const g of ["", ...DRAFT_GROUPS]) {
    const pill = el("button", "week-pill" + (faView.pos === g ? " active" : ""), g === "" ? "All" : g === "Specialists" ? "SPEC" : g);
    pill.type = "button";
    pill.addEventListener("click", () => {
      faView.pos = g;
      faView.showAllCols = false;
      faView.showAll = false;
      resetSortIfHidden();
      for (const b of posPills.children) b.classList.toggle("active", b === pill);
      renderGrid();
    });
    posPills.appendChild(pill);
  }
  view.appendChild(posPills);

  // Everything below the pills depends on q/team/pos/sort state, so it all lives
  // in one container the handlers can rebuild without touching the controls.
  const gridWrap = el("div");
  view.appendChild(gridWrap);

  function currentRatingCols() {
    return faView.showAllCols ? Object.keys(RATING_NAMES) : (GROUP_RATING_COLS[faView.pos] || GROUP_RATING_COLS[""]);
  }
  // A rating sort only survives a column-set change if the column is still shown —
  // otherwise the table would silently reorder by the fallback with a stale arrow.
  function resetSortIfHidden() {
    if (RATING_NAMES[faView.sort.col] && !currentRatingCols().includes(faView.sort.col)) faView.sort = { col: "ovr", dir: -1 };
  }

  function renderGrid() {
    gridWrap.replaceChildren();

    // Advisement strip: your identity + biggest needs, as context — not a filter.
    if (faView.teamId) {
      const tend = (DATA.tendencies || {})[String(faView.teamId)];
      const needs = ((DATA.needs || {})[String(faView.teamId)] || []).filter((n) => n.level === "HIGH" || n.level === "MEDIUM").slice(0, 3);
      const bits = [];
      if (tend) bits.push(`you run ${tend.runPct}% / throw ${100 - tend.runPct}%`);
      if (needs.length) bits.push("biggest needs: " + needs.map((n) => n.short || n.label).join(", "));
      if (bits.length) gridWrap.appendChild(el("div", "fa-advice", `${team(faView.teamId).nick} — ${bits.join(" · ")}`));
    }

    const q = faView.q.trim().toLowerCase();
    const scored = pool
      .filter((p) => !faView.pos || (DRAFT_GROUP_POS[faView.pos] || []).includes(p.pos))
      .filter((p) => !q || p.name.toLowerCase().includes(q))
      .map((p) => (faView.teamId ? { ...p, fit: fitFor(p, faView.teamId) } : p));

    const ratingCols = currentRatingCols();
    const cols = [
      { key: "name", label: "Player", title: "Player", sort: (p) => p.name, asc: true },
      { key: "pos", label: "POS", title: "Position", sort: (p) => p.pos, asc: true },
      { key: "age", label: "AGE", title: "Age", sort: (p) => p.age },
      { key: "dev", label: "DEV", title: "Dev trait", sort: (p) => DEV_ORDER[p.dev] ?? -1 },
      { key: "ovr", label: "OVR", title: "Overall", sort: (p) => p.ovr },
      { key: "value", label: "VALUE", title: "Trade value", sort: (p) => p.value },
      ...(faView.teamId ? [{ key: "fit", label: "FIT", title: "Fit for your roster (tap row for why)", sort: (p) => p.fit.score }] : []),
      ...ratingCols.map((k) => ({ key: k, label: k.toUpperCase(), title: RATING_NAMES[k], sort: (p) => (p.rat && p.rat[k] != null ? p.rat[k] : -1) })),
    ];

    const colDef = cols.find((c) => c.key === faView.sort.col) || cols[4];
    scored.sort((a, b) => {
      const va = colDef.sort(a), vb = colDef.sort(b);
      return (va < vb ? -1 : va > vb ? 1 : 0) * faView.sort.dir || b.ovr - a.ovr;
    });

    const wrap = el("div", "card table-wrap");
    const table = el("table", "roster-table fa-table");
    const thead = el("thead");
    const headRow = el("tr");
    for (const col of cols) {
      const th = el("th", faView.sort.col === col.key ? "sorted" : "");
      th.textContent = col.label + (faView.sort.col === col.key ? (faView.sort.dir === -1 ? " ▾" : " ▴") : "");
      th.title = col.title;
      th.addEventListener("click", () => {
        if (faView.sort.col === col.key) faView.sort.dir *= -1;
        else faView.sort = { col: col.key, dir: col.asc ? 1 : -1 };
        renderGrid();
      });
      headRow.appendChild(th);
    }
    thead.appendChild(headRow);
    table.appendChild(thead);

    const tbody = el("tbody");
    const CHUNK = 120;
    const shown = faView.showAll ? scored : scored.slice(0, CHUNK);
    for (const p of shown) {
      const tr = el("tr", "fa-row row-tappable");
      tr.addEventListener("click", () => openPlayerCard(p.id));
      const nameTd = el("td", "rt-name");
      nameTd.appendChild(avatar({ name: p.name, teamId: -1, portraitId: p.portraitId }));
      nameTd.appendChild(el("span", null, p.name));
      tr.appendChild(nameTd);
      tr.appendChild(el("td", null, p.pos));
      tr.appendChild(el("td", "rt-num", String(p.age ?? "—")));
      const devTd = el("td");
      devTd.appendChild(el("span", "dev-badge dev-" + (p.dev || "Normal").toLowerCase().replace(/[^a-z]/g, ""), p.dev || "—"));
      tr.appendChild(devTd);
      tr.appendChild(el("td", "rt-num", String(p.ovr)));
      tr.appendChild(el("td", "rt-num", p.value.toLocaleString()));
      if (faView.teamId) {
        const fitTd = el("td");
        fitTd.appendChild(el("span", "fit-badge fit-" + p.fit.verdict.toLowerCase().replace(/[^a-z]/g, ""), p.fit.verdict));
        tr.appendChild(fitTd);
      }
      for (const k of ratingCols) {
        const v = p.rat && p.rat[k] != null ? p.rat[k] : null;
        const cls = v == null ? "rt-num" : v >= 90 ? "rt-num rt-hi" : v >= 80 ? "rt-num rt-good" : v < 70 ? "rt-num rt-low" : "rt-num";
        tr.appendChild(el("td", cls, v == null ? "—" : String(v)));
      }
      tbody.appendChild(tr);
    }
    table.appendChild(tbody);
    wrap.appendChild(table);
    if (!scored.length) wrap.appendChild(el("div", "empty", "No free agents match."));
    gridWrap.appendChild(wrap);

    if (!faView.showAll && scored.length > CHUNK) {
      const more = el("button", "trade-cta fa-more", `Show all ${scored.length} players`);
      more.type = "button";
      more.addEventListener("click", () => { faView.showAll = true; renderGrid(); });
      gridWrap.appendChild(more);
    }
    const colsBtn = el("button", "csv-all-link fa-cols-toggle", faView.showAllCols ? "Show position-relevant columns" : "+ Show ALL 37 rating columns");
    colsBtn.type = "button";
    colsBtn.addEventListener("click", () => {
      faView.showAllCols = !faView.showAllCols;
      resetSortIfHidden();
      renderGrid();
    });
    gridWrap.appendChild(colsBtn);
    gridWrap.appendChild(el("div", "news-disclaimer", "Columns default to what scouts weigh for the position — sort by any of them, or open all 37. Fit is advisement (need + starter comparison + upside from real synced data); it never hides a player. EA's export has no personality, scheme, or formation data, so nothing here pretends to."));
  }

  renderGrid();
}

/* ---------- Teams directory ---------- */

function renderTeams(view) {
  const hqBtn = el("button", "trade-cta hq-btn", "🏈 DRAFT HQ — league needs · best available · pick values");
  hqBtn.type = "button";
  hqBtn.addEventListener("click", openDraftHq);
  view.appendChild(hqBtn);
  view.appendChild(sectionHead("Teams", "tap a team for roster, results & CSV"));
  const grid = el("div", "teams-grid");
  const sorted = [...(DATA.teams || [])].sort((a, b) => a.nick.localeCompare(b.nick));
  for (const t of sorted) {
    const card = el("button", "team-card");
    card.type = "button";
    card.style.setProperty("--tc", railColor(t.abbr));
    card.addEventListener("click", () => openTeam(t.teamId));
    card.appendChild(logoImg(t.abbr, "team-card-logo"));
    card.appendChild(el("div", "team-card-nick", t.nick));
    card.appendChild(el("div", "team-card-sub", `${record(t.teamId) || "—"}${t.owner ? " · " + t.owner : ""}`));
    grid.appendChild(card);
  }
  view.appendChild(grid);
}

/* ---------- Player lookup ---------- */

const playerSearch = { q: "", pos: "" }; // transient, survives re-renders
const POS_FILTERS = ["QB", "HB", "WR", "TE", "OL", "EDGE", "DT", "LB", "CB", "S", "K/P"];
const POS_GROUPS = {
  OL: ["LT", "LG", "C", "RG", "RT", "LS"],
  EDGE: ["LEDG", "REDG"],
  LB: ["MIKE", "WILL", "SAM"],
  S: ["SS", "FS"],
  "K/P": ["K", "P"],
};

function renderPlayers(view) {
  view.appendChild(sectionHead("Players", "every rostered player in the league"));

  const search = el("input", "roster-search");
  search.type = "search";
  search.placeholder = "Search by name…";
  search.value = playerSearch.q;
  search.addEventListener("input", () => { playerSearch.q = search.value; renderResults(); });
  view.appendChild(search);

  const pills = el("div", "week-pills");
  for (const pos of POS_FILTERS) {
    const pill = el("button", "week-pill" + (playerSearch.pos === pos ? " active" : ""), pos);
    pill.type = "button";
    pill.addEventListener("click", () => {
      playerSearch.pos = playerSearch.pos === pos ? "" : pos;
      render();
    });
    pills.appendChild(pill);
  }
  view.appendChild(pills);

  const card = el("div", "card");
  const list = el("div");
  card.appendChild(list);
  view.appendChild(card);
  const foot = el("div", "news-disclaimer");
  view.appendChild(foot);

  function matchesPos(p) {
    if (!playerSearch.pos) return true;
    const group = POS_GROUPS[playerSearch.pos];
    return group ? group.includes(p.pos) : p.pos === playerSearch.pos;
  }

  function renderResults() {
    const q = playerSearch.q.trim().toLowerCase();
    const rows = [];
    for (const [teamId, roster] of Object.entries(DATA.rosters || {})) {
      for (const p of roster) {
        if (!matchesPos(p)) continue;
        if (q && !p.name.toLowerCase().includes(q)) continue;
        rows.push({ ...p, teamId: Number(teamId) });
      }
    }
    rows.sort((a, b) => b.ovr - a.ovr || b.value - a.value);
    const shown = rows.slice(0, 50);
    list.replaceChildren();
    for (const p of shown) {
      const r = el("button", "player-row");
      r.type = "button";
      r.addEventListener("click", () => openPlayerCard(p.id));
      r.appendChild(avatar({ name: p.name, teamId: p.teamId, portraitId: p.portraitId }));
      const who = el("div", "wire-who");
      who.appendChild(el("div", "wire-name", p.name));
      who.appendChild(el("div", "wire-sub", `${p.pos} · ${team(p.teamId).nick} · ${p.age} yrs`));
      r.appendChild(who);
      const devWrap = el("span", "player-dev");
      devWrap.appendChild(el("span", "dev-badge dev-" + (p.dev || "Normal").toLowerCase().replace(/[^a-z]/g, ""), p.dev || "—"));
      r.appendChild(devWrap);
      r.appendChild(el("span", "player-ovr", String(p.ovr)));
      list.appendChild(r);
    }
    if (!shown.length) list.appendChild(el("div", "empty", "No players match."));
    foot.textContent = rows.length > 50 ? `Showing the top 50 of ${rows.length} matches — narrow the search or tap a position.` : "Tap a player for their full card — ratings, stats, contract. CSV export lives on the team page.";
  }
  renderResults();
}

/* ---------- App shell ---------- */

const RENDERERS = { home: renderHome, teams: renderTeams, players: renderPlayers, freeagents: renderFreeAgents, standings: renderStandings, rankings: renderRankings, leaders: renderLeaders, news: renderNews, trade: renderTrade };
let activeTab = "home";
let lastRenderedTab = null;
let viewTeamId = null; // non-null = the team detail page is open over the current tab
let viewDraftHq = false; // the league-wide Draft HQ page
const teamSort = { col: "ovr", dir: -1 }; // roster table sort state, survives re-renders
const needsView = { sort: "need", open: null }; // draft board: sort mode + which group is expanded
let scoreWeek = null; // "stage-week" key of a past week being browsed on Home, null = current week
let expandedGame = null; // scheduleId of the game card expanded into its matchup panel

function openTeam(teamId) {
  viewTeamId = teamId;
  needsView.open = null;
  try { history.pushState({ team: teamId }, "", "#team-" + teamId); } catch {}
  render();
}
function closeTeam(viaHistory) {
  viewTeamId = null;
  if (!viaHistory) { try { history.pushState(null, "", location.pathname + location.search); } catch {} }
  render();
}
function openDraftHq() {
  viewDraftHq = true;
  viewTeamId = null;
  try { history.pushState({ draft: true }, "", "#draft"); } catch {}
  render();
}
window.addEventListener("popstate", () => {
  const m = (location.hash || "").match(/^#team-(\d+)$/);
  viewTeamId = m ? Number(m[1]) : null;
  viewDraftHq = (location.hash || "") === "#draft";
  render();
});

function render() {
  const view = document.getElementById("view");
  const keepScroll = lastRenderedTab === activeTab;
  const y = window.scrollY;
  view.replaceChildren();
  if (!DATA) { view.appendChild(el("div", "loading", "Loading league data…")); return; }
  if (viewDraftHq) { renderDraftHq(view); lastRenderedTab = "draft-hq"; window.scrollTo(0, keepScroll ? y : 0); return; }
  if (viewTeamId != null) { renderTeam(view, viewTeamId); lastRenderedTab = "team-" + viewTeamId; window.scrollTo(0, keepScroll ? y : 0); return; }
  RENDERERS[activeTab](view);
  lastRenderedTab = activeTab;
  // Re-rendering the SAME tab (the trade builder does this on every tap) keeps the
  // scroll position; switching tabs starts at the top like a page change should.
  window.scrollTo(0, keepScroll ? y : 0);
}

for (const btn of document.querySelectorAll(".tab")) {
  btn.addEventListener("click", () => {
    viewTeamId = null;
    viewDraftHq = false;
    try { history.replaceState(null, "", location.pathname + location.search); } catch {}
    activeTab = btn.dataset.tab;
    for (const b of document.querySelectorAll(".tab")) {
      b.classList.toggle("active", b === btn);
      b.setAttribute("aria-selected", String(b === btn));
    }
    render();
  });
}

async function load() {
  try {
    const res = await fetch("site.json", { cache: "no-cache" });
    DATA = await res.json();
  } catch {
    // Offline / fetch failed — the SW may still have served a cached copy via the
    // fetch handler; if not, show the shell's empty state.
    if (!DATA) {
      document.getElementById("view").replaceChildren(el("div", "empty", "Can't reach the league right now — try again when you're back online."));
      return;
    }
  }
  teamIndex.clear();
  for (const t of DATA.teams || []) teamIndex.set(t.teamId, t);
  document.getElementById("week-chip").textContent = DATA.weekLabel || "—";
  const m = (location.hash || "").match(/^#team-(\d+)$/);
  if (m) viewTeamId = Number(m[1]);
  if ((location.hash || "") === "#draft") viewDraftHq = true;
  render();
}

/* Magic-link setup: /site-key DMs a personal link ending in #k=FOK1... — tapping
   it lands here, we store the key and scrub it from the URL immediately. The
   fragment never reaches any server (fragments aren't sent in requests), so the
   key exists only in the DM and this device. */
(function keyFromLink() {
  const m = (location.hash || "").match(/[#&]k=(FOK1\.[0-9]+\.[A-Za-z0-9_-]+)/);
  if (!m) return;
  try { localStorage.setItem("site-key", m[1]); } catch {}
  history.replaceState(null, "", location.pathname + location.search);
})();

/* iOS install hint — Safari has no install prompt, so surface the one-time how-to. */
(function iosHint() {
  const isIos = /iphone|ipad|ipod/i.test(navigator.userAgent);
  const standalone = window.matchMedia("(display-mode: standalone)").matches || window.navigator.standalone === true;
  let dismissed = false;
  try { dismissed = localStorage.getItem("ios-hint-dismissed") === "1"; } catch {}
  if (isIos && !standalone && !dismissed) {
    const hint = document.getElementById("ios-hint");
    hint.hidden = false;
    document.getElementById("ios-hint-close").addEventListener("click", () => {
      hint.hidden = true;
      try { localStorage.setItem("ios-hint-dismissed", "1"); } catch {}
    });
  }
})();

if ("serviceWorker" in navigator) {
  navigator.serviceWorker.register("sw.js").catch(() => {});
}

load();
